window.RoomBridgeAPI = {
  async request(path, options={}) {
    const response=await fetch(`/api${path}`,{credentials:"same-origin",headers:{"Content-Type":"application/json",...(options.headers||{})},...options,body:options.body&&typeof options.body!=="string"?JSON.stringify(options.body):options.body});
    const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;
  },
  health(){return this.request("/health")},
  me(){return this.request("/auth/me")},
  register(data){return this.request("/auth/register",{method:"POST",body:data})},
  verify(data){return this.request("/auth/verify",{method:"POST",body:data})},
  resendCode(verificationId){return this.request("/auth/resend",{method:"POST",body:{verificationId}})},
  requestContactVerification(data){return this.request("/auth/request-verification",{method:"POST",body:data})},
  login(data){return this.request("/auth/login",{method:"POST",body:data})},
  requestPasswordReset(email){return this.request("/auth/password-reset/request",{method:"POST",body:{email}})},
  confirmPasswordReset(data){return this.request("/auth/password-reset/confirm",{method:"POST",body:data})},
  logout(){return this.request("/auth/logout",{method:"POST"})},
  exportAccount(){return this.request("/account/export")},
  deleteAccount(password){return this.request("/account",{method:"DELETE",body:{password}})},
  blockUser(id,blocked=true){return this.request(`/blocks/${id}`,{method:blocked?"POST":"DELETE",body:blocked?{}:undefined})},
  enforcements(){return this.request("/enforcements")},
  appeal(data){return this.request("/appeals",{method:"POST",body:data})},
  report(data){return this.request("/reports",{method:"POST",body:data})},
  adminQueue(){return this.request("/admin/queue")},
  moderateReport(id,data){return this.request(`/admin/reports/${id}`,{method:"PATCH",body:data})},
  moderateListing(id,data){return this.request(`/admin/listings/${id}`,{method:"PATCH",body:data})},
  moderateVerification(id,data){return this.request(`/admin/verifications/${id}`,{method:"PATCH",body:data})},
  enforceUser(id,data){return this.request(`/admin/users/${id}/enforcements`,{method:"POST",body:data})},
  decideAppeal(id,data){return this.request(`/admin/appeals/${id}`,{method:"PATCH",body:data})},
  profile(){return this.request("/profile")},
  saveProfile(data){return this.request("/profile",{method:"PUT",body:data})},
  lifeState(){return this.request("/life-state")},
  saveLifeState(data){return this.request("/life-state",{method:"PUT",body:{data}})},
  listings(filters={}){return this.request(`/listings?${new URLSearchParams(filters)}`)},
  myListings(){return this.request("/listings/mine")},
  createListing(data,idempotencyKey=crypto.randomUUID()){return this.request("/listings",{method:"POST",headers:{"Idempotency-Key":idempotencyKey},body:data})},
  saveSearch(data){return this.request("/saved-searches",{method:"POST",body:data})},
  savedSearches(){return this.request("/saved-searches")},
  updateSavedSearch(id,data){return this.request(`/saved-searches/${id}`,{method:"PATCH",body:data})},
  deleteSavedSearch(id){return this.request(`/saved-searches/${id}`,{method:"DELETE"})},
  requestVerification(data){return this.request("/verifications",{method:"POST",body:data})},
  matches(){return this.request("/matches")},
  matchFeedback(candidateId,feedback){return this.request("/match-feedback",{method:"POST",body:{candidateId,feedback}})},
  savedProfiles(){return this.request("/saved-profiles")},
  saveProfileCard(id,saved=true){return this.request(`/saved-profiles/${id}`,{method:saved?"PUT":"DELETE"})},
  conversations(){return this.request("/conversations")},
  createConversation(data){return this.request("/conversations",{method:"POST",body:data})},
  messages(id){return this.request(`/conversations/${id}/messages`)},
  sendMessage(id,data,idempotencyKey=crypto.randomUUID()){return this.request(`/conversations/${id}/messages`,{method:"POST",headers:{"Idempotency-Key":idempotencyKey},body:data})},
  blockConversation(id,blocked=true){return this.request(`/conversations/${id}/block`,{method:blocked?"POST":"DELETE"})},
  households(){return this.request("/households")},
  household(id){return this.request(`/households/${id}`)},
  createHousehold(data){return this.request("/households",{method:"POST",body:data})},
  updateHousehold(id,data){return this.request(`/households/${id}`,{method:"PATCH",body:data})},
  addHouseholdMember(id,userId){return this.request(`/households/${id}/members`,{method:"POST",body:{userId}})},
  removeHouseholdMember(id,userId){return this.request(`/households/${id}/members/${userId}`,{method:"DELETE"})},
  leaseWorkflows(){return this.request("/lease-workflows")},
  createLeaseWorkflow(data){return this.request("/lease-workflows",{method:"POST",body:data})},
  updateLeaseWorkflow(id,data){return this.request(`/lease-workflows/${id}`,{method:"PATCH",body:data})},
  createUploadIntent(data){return this.request("/uploads/intents",{method:"POST",body:data})},
  completeUpload(id){return this.request(`/uploads/${id}/complete`,{method:"POST",body:{}})},
  uploadDownload(id){return this.request(`/uploads/${id}/download`)},
  async uploadFile(file,purpose,targetId){
    const intent=await this.createUploadIntent({filename:file.name,contentType:file.type,byteSize:file.size,purpose,targetId});
    const response=await fetch(intent.uploadUrl,{method:"PUT",headers:intent.headers,body:file});
    if(!response.ok)throw new Error(`Upload failed (${response.status})`);
    return this.completeUpload(intent.id);
  },
  translate(text,targetLanguage){return this.request("/ai/translate",{method:"POST",body:{text,targetLanguage}})},
  events(onEvent){const events=new EventSource("/api/events");events.addEventListener("message",e=>onEvent("message",JSON.parse(e.data)));return events;}
};
