import http from "node:http";
import { randomUUID as requestUuid } from "node:crypto";
import { readFileSync, existsSync, statSync } from "node:fs";
import { extname, resolve, sep } from "node:path";
import { sql, databaseKind, databaseReady } from "./database.js";
import { passwordHash,passwordValid,createSession,sessionUser,clearSession,issueCode,consumeCode,randomUUID } from "./auth.js";
import { config, assertProductionConfiguration } from "./config.js";
import { ValidationError, registration, login as validateLogin, verification as validateVerification, profile as validateProfile, listing as validateListing } from "./validation.js";
import { rateLimit } from "./rate-limit.js";
import { audit } from "./audit.js";
import { canManageHousehold, canManageListing, requireAnyRole } from "./authorization.js";
import { storageConfigured, validateUpload, objectKey, signUpload, verifyObject, signDownload } from "./storage.js";
import { redisConfigured, redisReady } from "./redis.js";
import { observeRequest, metrics } from "./observability.js";
import { subscribeUser, publishUser } from "./realtime.js";
import { cacheGet, cacheSet, cacheDeletePrefix } from "./cache.js";
import { scoreProfiles } from "./services/matching.js";
import { fraudSignal,translate,personalizedRerank } from "./services/ai.js";
import { commuteEstimate } from "./services/maps.js";
import { notify } from "./services/notifications.js";

assertProductionConfiguration();
const root=resolve(import.meta.dirname,"..");
const mime={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json",".svg":"image/svg+xml"};
const json=(res,status,data,headers={})=>{res.writeHead(status,{"Content-Type":"application/json; charset=utf-8",...headers});res.end(JSON.stringify(data))};
const cookie=session=>`rb_session=${encodeURIComponent(session.token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${config.sessionDays*86400}${config.production?'; Secure':''}`;
async function body(req){if(!String(req.headers["content-type"]||"").toLowerCase().startsWith("application/json"))throw new ValidationError("Content-Type must be application/json");let raw="";for await(const chunk of req){raw+=chunk;if(raw.length>config.bodyLimit)throw new ValidationError("Request body is too large")}try{return raw?JSON.parse(raw):{}}catch{throw new ValidationError("Request body must be valid JSON")}}
const publicUser=u=>u&&({id:u.id,email:u.email,name:u.name,phone:u.phone,emailVerified:!!u.email_verified,phoneVerified:!!u.phone_verified,institutionVerified:!!u.institution_verified,reputation:u.reputation,locale:u.locale,currency:u.currency});
async function requireUser(req,res){const user=await sessionUser(req);if(!user)json(res,401,{error:"Authentication required"});return user}
const parseJson=(value,fallback)=>typeof value==="string"?JSON.parse(value||JSON.stringify(fallback)):(value??fallback);
function parseProfile(row){return row&&{...row,languages:parseJson(row.languages,[]),lifestyle:parseJson(row.lifestyle,{}),weights:parseJson(row.preference_weights,{}),dealBreakers:parseJson(row.deal_breakers,{})}}
function pageParams(url,{defaultLimit=25,maxLimit=100}={}){const limit=Math.min(maxLimit,Math.max(1,Number(url.searchParams.get("limit"))||defaultLimit)),cursor=Math.max(0,Number(url.searchParams.get("cursor"))||0);return{limit,cursor,next:rows=>rows.length===limit?cursor+limit:null}}
function idempotencyKey(req){const value=req.headers["idempotency-key"];if(value!==undefined&&!/^[A-Za-z0-9._:-]{8,100}$/.test(String(value)))throw new ValidationError("Idempotency-Key must be 8–100 safe characters");return value?String(value):null}
async function idempotencyReplay(userId,key,route,res){if(!key)return false;const saved=await sql.one("SELECT status,response FROM idempotency_keys WHERE user_id=? AND key=? AND route=? AND expires_at>CURRENT_TIMESTAMP",userId,key,route);if(!saved)return false;json(res,Number(saved.status),parseJson(saved.response,{}),{"Idempotency-Replayed":"true"});return true}

async function api(req,res,url){
  if(req.method==="GET"&&url.pathname==="/api/health/live")return json(res,200,{ok:true});
  if(req.method==="GET"&&url.pathname==="/api/health"){await databaseReady;await sql.one("SELECT 1 AS ready");const cache=redisConfigured()?await redisReady():!config.production;return json(res,cache?200:503,{ok:cache,database:databaseKind,cache:redisConfigured()?"redis":"local-development",storage:storageConfigured()?"configured":"unavailable",realtime:"sse",ai:process.env.OPENAI_API_KEY?"configured":"fallback"})}
  if(req.method==="POST"&&url.pathname==="/api/auth/register"){
    if(!await rateLimit(req,res,{key:"register",limit:5,windowMs:15*60_000}))return;
    const d=registration(await body(req)),id=randomUUID();try{await sql.run("INSERT INTO users(id,email,password_hash,name) VALUES(?,?,?,?)",id,d.email,passwordHash(d.password),d.name)}catch{await audit(req,"auth.register",{outcome:"rejected",metadata:{reason:"duplicate"}});return json(res,409,{error:"Unable to create account with those details"})}
    const verification=await issueCode(id,d.email,"email");await audit(req,"auth.register",{actorId:id,targetType:"user",targetId:id});return json(res,201,{userId:id,verificationId:verification.id,...(config.production?{}:{demoCode:verification.code})});
  }
  if(req.method==="POST"&&url.pathname==="/api/auth/verify"){
    if(!await rateLimit(req,res,{key:"verify",limit:10,windowMs:15*60_000}))return;
    const d=validateVerification(await body(req)),v=await consumeCode(d.verificationId,d.code);if(!v){await audit(req,"auth.verify",{outcome:"rejected"});return json(res,400,{error:"Invalid or expired code"})}
    if(v.purpose==="email")await sql.run("UPDATE users SET email_verified=1 WHERE id=?",v.user_id);if(v.purpose==="phone")await sql.run("UPDATE users SET phone_verified=1,phone=? WHERE id=?",v.destination,v.user_id);if(v.purpose==="institution")await sql.run("UPDATE users SET institution_verified=1 WHERE id=?",v.user_id);
    const session=await createSession(v.user_id);await audit(req,"auth.verify",{actorId:v.user_id,targetType:"user",targetId:v.user_id});return json(res,200,{user:publicUser(await sql.one("SELECT * FROM users WHERE id=?",v.user_id))},{"Set-Cookie":cookie(session)});
  }
  if(req.method==="POST"&&url.pathname==="/api/auth/login"){
    if(!await rateLimit(req,res,{key:"login",limit:10,windowMs:15*60_000}))return;
    const d=validateLogin(await body(req)),u=await sql.one("SELECT * FROM users WHERE email=?",d.email);if(!u||!passwordValid(d.password,u.password_hash)){await audit(req,"auth.login",{outcome:"rejected"});return json(res,401,{error:"Invalid credentials"})}if(!u.email_verified)return json(res,403,{error:"Email verification required"});const enforcement=await sql.one("SELECT action,expires_at FROM user_enforcements WHERE user_id=? AND action IN ('suspension','ban') AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>CURRENT_TIMESTAMP) ORDER BY starts_at DESC LIMIT 1",u.id);if(enforcement)return json(res,403,{error:"Account access is restricted",code:"account_restricted"});const session=await createSession(u.id);await audit(req,"auth.login",{actorId:u.id,targetType:"user",targetId:u.id});return json(res,200,{user:publicUser(u)},{"Set-Cookie":cookie(session)});
  }
  if(req.method==="POST"&&url.pathname==="/api/auth/resend"){
    if(!await rateLimit(req,res,{key:"resend",limit:5,windowMs:30*60_000}))return;
    const d=await body(req),previous=await sql.one("SELECT user_id,destination,purpose FROM verification_codes WHERE id=?",d.verificationId);if(!previous)return json(res,404,{error:"Verification request not found"});const v=await issueCode(previous.user_id,previous.destination,previous.purpose);return json(res,201,{verificationId:v.id,...(process.env.NODE_ENV==='production'?{}:{demoCode:v.code})});
  }
  if(req.method==="POST"&&url.pathname==="/api/auth/password-reset/request"){
    if(!await rateLimit(req,res,{key:"password-reset",limit:5,windowMs:30*60_000}))return;
    const d=await body(req),normalized=String(d.email||"").trim().toLowerCase(),user=await sql.one("SELECT id,email FROM users WHERE email=?",normalized);
    let verification;if(user)verification=await issueCode(user.id,user.email,"password_reset");
    await audit(req,"auth.password_reset_requested",{actorId:user?.id,targetType:"user",targetId:user?.id});
    return json(res,202,{ok:true,message:"If that account exists, a reset code has been sent.",...(!config.production&&verification?{verificationId:verification.id,demoCode:verification.code}:{})});
  }
  if(req.method==="POST"&&url.pathname==="/api/auth/password-reset/confirm"){
    if(!await rateLimit(req,res,{key:"password-reset-confirm",limit:10,windowMs:30*60_000}))return;
    const d=await body(req),checked=validateVerification(d),newPassword=registration({name:"Reset User",email:"reset@example.com",password:d.password}).password,v=await consumeCode(checked.verificationId,checked.code);
    if(!v||v.purpose!=="password_reset")return json(res,400,{error:"Invalid or expired reset code"});
    await sql.transaction(async tx=>{await tx.run("UPDATE users SET password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",passwordHash(newPassword),v.user_id);await tx.run("DELETE FROM sessions WHERE user_id=?",v.user_id)});
    await audit(req,"auth.password_reset_completed",{actorId:v.user_id,targetType:"user",targetId:v.user_id});
    return json(res,200,{ok:true});
  }
  if(req.method==="POST"&&url.pathname==="/api/auth/logout"){const current=await sessionUser(req);await clearSession(req);await audit(req,"auth.logout",{actorId:current?.id,targetType:"user",targetId:current?.id});return json(res,200,{ok:true},{"Set-Cookie":"rb_session=; Path=/; HttpOnly; Max-Age=0; SameSite=Lax"})}
  if(req.method==="GET"&&url.pathname==="/api/auth/me"){const u=await requireUser(req,res);if(u)return json(res,200,{user:publicUser(u)});return}
  if(req.method==="POST"&&url.pathname==="/api/auth/request-verification"){const u=await requireUser(req,res);if(!u)return;const d=await body(req),v=await issueCode(u.id,d.destination,d.purpose);return json(res,201,{verificationId:v.id,...(process.env.NODE_ENV==='production'?{}:{demoCode:v.code})})}
  if(req.method==="GET"&&url.pathname==="/api/events"){const u=await requireUser(req,res);if(!u)return;res.writeHead(200,{"Content-Type":"text/event-stream","Cache-Control":"no-cache, no-transform","Connection":"keep-alive","X-Accel-Buffering":"no"});res.write(`event: ready\ndata: {"ok":true}\n\n`);const unsubscribe=await subscribeUser(u.id,message=>res.write(`event: ${message.event}\ndata: ${JSON.stringify(message.payload)}\n\n`)),heartbeat=setInterval(()=>res.write(": heartbeat\n\n"),20_000);req.on("close",()=>{clearInterval(heartbeat);unsubscribe()});return}

  const u=await requireUser(req,res);if(!u)return;
  if(url.pathname==="/api/uploads/intents"&&req.method==="POST"){
    if(!storageConfigured())return json(res,503,{error:"File storage is not configured",code:"storage_unavailable"});
    const d=await body(req);try{validateUpload(d)}catch(error){return json(res,400,{error:error.message})}
    let allowed=false;
    if(d.purpose==="listing_media")allowed=await canManageListing(u.id,d.targetId);
    if(d.purpose==="message_attachment")allowed=!!await sql.one("SELECT 1 FROM conversation_members WHERE conversation_id=? AND user_id=?",d.targetId,u.id);
    if(d.purpose==="verification_document")allowed=!!await sql.one("SELECT 1 FROM verification_requests WHERE id=? AND user_id=?",d.targetId,u.id);
    if(d.purpose==="lease_document")allowed=!!await sql.one("SELECT 1 FROM lease_workflows WHERE id=? AND (outgoing_user_id=? OR incoming_user_id=?)",d.targetId,u.id,u.id);
    if(!allowed)return json(res,403,{error:"You cannot attach files to that resource"});
    const id=randomUUID(),key=objectKey(u.id,d.purpose,d.contentType),expires=new Date(Date.now()+10*60_000).toISOString();
    await sql.transaction(async tx=>{await tx.run("INSERT INTO upload_intents(id,user_id,purpose,object_key,filename,content_type,byte_size,expires_at) VALUES(?,?,?,?,?,?,?,?)",id,u.id,d.purpose,key,d.filename,d.contentType,Number(d.byteSize),expires);await tx.run("INSERT INTO upload_bindings(upload_id,target_type,target_id) VALUES(?,?,?)",id,d.purpose,d.targetId)});
    const uploadUrl=await signUpload(key,d.contentType,d.byteSize);await audit(req,"upload.intent",{actorId:u.id,targetType:d.purpose,targetId:d.targetId,metadata:{uploadId:id,contentType:d.contentType,byteSize:d.byteSize}});
    return json(res,201,{id,uploadUrl,expiresAt:expires,headers:{"Content-Type":d.contentType,"x-amz-server-side-encryption":"AES256"}});
  }
  const uploadComplete=url.pathname.match(/^\/api\/uploads\/([^/]+)\/complete$/);if(uploadComplete&&req.method==="POST"){
    const intent=await sql.one("SELECT * FROM upload_intents WHERE id=? AND user_id=? AND status='pending' AND expires_at>CURRENT_TIMESTAMP",uploadComplete[1],u.id);if(!intent)return json(res,404,{error:"Upload intent not found or expired"});
    const object=await verifyObject(intent.object_key);if(Number(object.ContentLength)!==Number(intent.byte_size)||String(object.ContentType)!==intent.content_type)return json(res,400,{error:"Uploaded object does not match the signed intent"});
    const jobId=randomUUID();await sql.transaction(async tx=>{await tx.run("UPDATE upload_intents SET status='quarantined' WHERE id=?",intent.id);await tx.run("INSERT INTO jobs(id,kind,payload) VALUES(?,?,?)",jobId,"scan_upload",JSON.stringify({uploadId:intent.id,objectKey:intent.object_key,contentType:intent.content_type}))});
    return json(res,202,{id:intent.id,status:"quarantined",scanJobId:jobId});
  }
  const uploadDownload=url.pathname.match(/^\/api\/uploads\/([^/]+)\/download$/);if(uploadDownload&&req.method==="GET"){
    const row=await sql.one("SELECT ui.*,ub.target_type,ub.target_id FROM upload_intents ui JOIN upload_bindings ub ON ub.upload_id=ui.id WHERE ui.id=? AND ui.status='clean'",uploadDownload[1]);if(!row)return json(res,404,{error:"File is unavailable"});
    let allowed=row.user_id===u.id;
    if(row.target_type==="message_attachment")allowed=!!await sql.one("SELECT 1 FROM conversation_members WHERE conversation_id=? AND user_id=?",row.target_id,u.id);
    if(row.target_type==="listing_media")allowed=!!await sql.one("SELECT 1 FROM listings WHERE id=? AND (owner_id=? OR status='active')",row.target_id,u.id);
    if(row.target_type==="lease_document")allowed=!!await sql.one("SELECT 1 FROM lease_workflows WHERE id=? AND (outgoing_user_id=? OR incoming_user_id=?)",row.target_id,u.id,u.id);
    if(!allowed)return json(res,403,{error:"Forbidden"});
    return json(res,200,{downloadUrl:await signDownload(row.object_key,row.filename),expiresIn:300});
  }
  if(url.pathname==="/api/account/export"&&req.method==="GET"){
    const [profile,listings,messages,households,reports]=await Promise.all([
      sql.one("SELECT * FROM profiles WHERE user_id=?",u.id),
      sql.all("SELECT * FROM listings WHERE owner_id=? ORDER BY created_at",u.id),
      sql.all("SELECT id,conversation_id,body,attachment_key,created_at FROM messages WHERE sender_id=? ORDER BY created_at",u.id),
      sql.all("SELECT h.* FROM households h JOIN household_members hm ON hm.household_id=h.id WHERE hm.user_id=?",u.id),
      sql.all("SELECT * FROM reports WHERE reporter_id=? ORDER BY created_at",u.id)
    ]);
    await audit(req,"account.export",{actorId:u.id,targetType:"user",targetId:u.id});
    return json(res,200,{exportedAt:new Date().toISOString(),user:publicUser(u),profile,listings,messages,households,reports});
  }
  if(url.pathname==="/api/account"&&req.method==="DELETE"){
    const d=await body(req),account=await sql.one("SELECT password_hash FROM users WHERE id=?",u.id);
    if(!account||!passwordValid(d.password||"",account.password_hash))return json(res,403,{error:"Password confirmation failed"});
    await audit(req,"account.delete",{actorId:u.id,targetType:"user",targetId:u.id});
    const tombstone=`deleted-${randomUUID()}@deleted.invalid`;
    await sql.transaction(async tx=>{
      await tx.run("DELETE FROM sessions WHERE user_id=?",u.id);
      await tx.run("DELETE FROM profiles WHERE user_id=?",u.id);
      await tx.run("DELETE FROM saved_searches WHERE user_id=?",u.id);
      await tx.run("UPDATE users SET email=?,name='Deleted user',phone=NULL,password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",tombstone,passwordHash(randomUUID()+randomUUID()),u.id);
    });
    return json(res,200,{ok:true},{"Set-Cookie":"rb_session=; Path=/; HttpOnly; Max-Age=0; SameSite=Lax"});
  }
  const userBlock=url.pathname.match(/^\/api\/blocks\/([^/]+)$/);if(userBlock&&req.method==="POST"){if(userBlock[1]===u.id||!await sql.one("SELECT 1 FROM users WHERE id=?",userBlock[1]))return json(res,400,{error:"Invalid user"});await sql.transaction(async tx=>{await tx.run("INSERT INTO user_blocks(blocker_id,blocked_id) VALUES(?,?) ON CONFLICT DO NOTHING",u.id,userBlock[1]);await tx.run(`UPDATE conversation_members SET blocked_at=CURRENT_TIMESTAMP WHERE user_id=? AND conversation_id IN
    (SELECT mine.conversation_id FROM conversation_members mine JOIN conversation_members other ON other.conversation_id=mine.conversation_id WHERE mine.user_id=? AND other.user_id=?)`,u.id,u.id,userBlock[1])});await audit(req,"user.block",{actorId:u.id,targetType:"user",targetId:userBlock[1]});return json(res,200,{ok:true})}
  if(userBlock&&req.method==="DELETE"){await sql.run("DELETE FROM user_blocks WHERE blocker_id=? AND blocked_id=?",u.id,userBlock[1]);await audit(req,"user.unblock",{actorId:u.id,targetType:"user",targetId:userBlock[1]});return json(res,200,{ok:true})}
  if(url.pathname==="/api/enforcements"&&req.method==="GET")return json(res,200,{enforcements:await sql.all("SELECT id,action,reason,starts_at,expires_at,revoked_at FROM user_enforcements WHERE user_id=? ORDER BY starts_at DESC",u.id)})
  if(url.pathname==="/api/appeals"&&req.method==="POST"){const d=await body(req),enforcement=await sql.one("SELECT 1 FROM user_enforcements WHERE id=? AND user_id=? AND revoked_at IS NULL",d.enforcementId,u.id);if(!enforcement)return json(res,404,{error:"Enforcement not found"});const statement=String(d.statement||"").trim();if(statement.length<20||statement.length>5000)return json(res,400,{error:"Appeal statement must be between 20 and 5000 characters"});const id=randomUUID();try{await sql.run("INSERT INTO moderation_appeals(id,user_id,enforcement_id,statement) VALUES(?,?,?,?)",id,u.id,d.enforcementId,statement)}catch{return json(res,409,{error:"An appeal already exists"})}return json(res,201,{id,status:"pending"})}
  if(url.pathname==="/api/profile"&&req.method==="GET")return json(res,200,{profile:parseProfile(await sql.one("SELECT * FROM profiles WHERE user_id=?",u.id))});
  if(url.pathname==="/api/profile"&&req.method==="PUT"){
    const d=validateProfile(await body(req));await sql.run(`INSERT INTO profiles(user_id,scenario,city,budget,room_type,move_date,lease_duration,country,diet,languages,bio,lifestyle,preference_weights,deal_breakers,public_status)
      VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET scenario=excluded.scenario,city=excluded.city,budget=excluded.budget,room_type=excluded.room_type,move_date=excluded.move_date,lease_duration=excluded.lease_duration,country=excluded.country,diet=excluded.diet,languages=excluded.languages,bio=excluded.bio,lifestyle=excluded.lifestyle,preference_weights=excluded.preference_weights,deal_breakers=excluded.deal_breakers,public_status=excluded.public_status,updated_at=CURRENT_TIMESTAMP`,u.id,d.scenario,d.city,d.budget,d.roomType,d.moveDate,d.leaseDuration,d.country,d.diet,JSON.stringify(d.languages||[]),d.bio,JSON.stringify(d.lifestyle||{}),JSON.stringify(d.weights||{}),JSON.stringify(d.dealBreakers||{}),d.publicStatus);return json(res,200,{ok:true});
  }
  if(url.pathname==="/api/life-state"&&req.method==="GET"){const row=await sql.one("SELECT data FROM life_state WHERE user_id=?",u.id);return json(res,200,{data:row?parseJson(row.data,{}):{}})}
  if(url.pathname==="/api/life-state"&&req.method==="PUT"){const d=await body(req),serialized=JSON.stringify(d.data||{});if(serialized.length>100_000)return json(res,400,{error:"Life Hub data is too large"});await sql.run("INSERT INTO life_state(user_id,data) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data,updated_at=CURRENT_TIMESTAMP",u.id,serialized);return json(res,200,{ok:true})}
  if(url.pathname==="/api/listings"&&req.method==="POST"){
    const route="/api/listings",key=idempotencyKey(req);if(await idempotencyReplay(u.id,key,route,res))return;
    const d=validateListing(await body(req)),id=randomUUID(),result={id,status:"pending_review"},expires=new Date(Date.now()+24*60*60_000).toISOString();
    try{await sql.transaction(async tx=>{await tx.run(`INSERT INTO listings(id,owner_id,title,description,category,city,neighborhood,exact_address,rent,deposit,available_date,lease_duration,furnished,utilities,parking,laundry,accessibility,amenities,latitude,longitude) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,id,u.id,d.title,d.description,d.category,d.city,d.neighborhood,d.exactAddress,d.rent,d.deposit,d.availableDate,d.leaseDuration,d.furnished,d.utilities,d.parking,d.laundry,d.accessibility,JSON.stringify(d.amenities||[]),d.latitude,d.longitude);if(key)await tx.run("INSERT INTO idempotency_keys(user_id,key,route,status,response,expires_at) VALUES(?,?,?,?,?,?)",u.id,key,route,201,JSON.stringify(result),expires)})}
    catch(error){if(await idempotencyReplay(u.id,key,route,res))return;throw error}
    await cacheDeletePrefix("listings:");await notify(u.id,"listing","Listing submitted","Your listing is awaiting moderation.");return json(res,201,result);
  }
  if(url.pathname==="/api/listings/mine"&&req.method==="GET"){const page=pageParams(url);const rows=await sql.all("SELECT * FROM listings WHERE owner_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?",u.id,page.limit,page.cursor);return json(res,200,{listings:rows.map(x=>({...x,amenities:typeof x.amenities==="string"?JSON.parse(x.amenities||"[]"):x.amenities||[]})),nextCursor:page.next(rows)})}
  if(url.pathname==="/api/listings"&&req.method==="GET"){
    const cacheKey=`listings:${[...url.searchParams.entries()].sort().map(x=>x.join("=")).join("&")}`,cached=await cacheGet(cacheKey);if(cached)return json(res,200,cached);
    const q=[],p=[];q.push("status='active'");for(const [key,col,op] of [["city","city","="],["category","category","="],["maxRent","rent","<="]])if(url.searchParams.get(key)){q.push(`${col}${op}?`);p.push(url.searchParams.get(key))}if(url.searchParams.get("moveBy")){q.push("available_date<=?");p.push(url.searchParams.get("moveBy"))}const rows=(await sql.all(`SELECT id,owner_id,title,description,category,city,neighborhood,rent,deposit,available_date,lease_duration,furnished,utilities,parking,laundry,accessibility,amenities,latitude,longitude,verification_status FROM listings WHERE ${q.join(" AND ")} ORDER BY created_at DESC`,...p)).map(x=>({...x,amenities:parseJson(x.amenities,[])})),result={listings:rows};await cacheSet(cacheKey,result,30);return json(res,200,result);
  }
  if(url.pathname==="/api/saved-searches"&&req.method==="POST"){const d=await body(req),id=randomUUID();await sql.run("INSERT INTO saved_searches(id,user_id,name,filters,alerts_enabled) VALUES(?,?,?,?,?)",id,u.id,d.name,JSON.stringify(d.filters||{}),d.alertsEnabled===false?0:1);return json(res,201,{id})}
  if(url.pathname==="/api/saved-searches"&&req.method==="GET")return json(res,200,{searches:(await sql.all("SELECT * FROM saved_searches WHERE user_id=? ORDER BY created_at DESC",u.id)).map(x=>({...x,filters:parseJson(x.filters,{})}))});
  const savedSearchMatch=url.pathname.match(/^\/api\/saved-searches\/([^/]+)$/);if(savedSearchMatch&&req.method==="PATCH"){const d=await body(req),owned=await sql.one("SELECT 1 FROM saved_searches WHERE id=? AND user_id=?",savedSearchMatch[1],u.id);if(!owned)return json(res,404,{error:"Saved search not found"});await sql.run("UPDATE saved_searches SET alerts_enabled=? WHERE id=? AND user_id=?",d.alertsEnabled===false?0:1,savedSearchMatch[1],u.id);return json(res,200,{ok:true})}
  if(savedSearchMatch&&req.method==="DELETE"){await sql.run("DELETE FROM saved_searches WHERE id=? AND user_id=?",savedSearchMatch[1],u.id);return json(res,200,{ok:true})}
  if(url.pathname==="/api/matches"&&req.method==="GET"){
    const mine=parseProfile(await sql.one("SELECT * FROM profiles WHERE user_id=?",u.id));if(!mine)return json(res,400,{error:"Complete profile first"});const candidates=(await sql.all(`SELECT p.*,usr.name,usr.reputation FROM profiles p JOIN users usr ON usr.id=p.user_id WHERE p.user_id<>?
      AND NOT EXISTS(SELECT 1 FROM user_blocks b WHERE (b.blocker_id=? AND b.blocked_id=p.user_id) OR (b.blocker_id=p.user_id AND b.blocked_id=?))
      AND NOT EXISTS(SELECT 1 FROM user_enforcements e WHERE e.user_id=p.user_id AND e.action IN ('suspension','ban') AND e.revoked_at IS NULL AND (e.expires_at IS NULL OR e.expires_at>CURRENT_TIMESTAMP))`,u.id,u.id,u.id)).map(parseProfile);const results=[];for(const c of candidates){const feedback=(await sql.one("SELECT feedback FROM match_feedback WHERE user_id=? AND candidate_id=?",u.id,c.user_id))?.feedback;results.push({...c,...scoreProfiles(mine,c,feedback)})}return json(res,200,{matches:await personalizedRerank(results)});
  }
  if(url.pathname==="/api/match-feedback"&&req.method==="POST"){const d=await body(req);await sql.run("INSERT INTO match_feedback(user_id,candidate_id,feedback) VALUES(?,?,?) ON CONFLICT(user_id,candidate_id) DO UPDATE SET feedback=excluded.feedback,created_at=CURRENT_TIMESTAMP",u.id,d.candidateId,d.feedback);return json(res,200,{ok:true})}
  if(url.pathname==="/api/saved-profiles"&&req.method==="GET")return json(res,200,{ids:(await sql.all("SELECT saved_user_id FROM saved_profiles WHERE user_id=? ORDER BY created_at DESC",u.id)).map(x=>x.saved_user_id)})
  const savedProfile=url.pathname.match(/^\/api\/saved-profiles\/([^/]+)$/);if(savedProfile&&req.method==="PUT"){const exists=await sql.one("SELECT 1 FROM users WHERE id=? AND id<>?",savedProfile[1],u.id);if(!exists)return json(res,404,{error:"Profile not found"});await sql.run("INSERT INTO saved_profiles(user_id,saved_user_id) VALUES(?,?) ON CONFLICT DO NOTHING",u.id,savedProfile[1]);return json(res,200,{ok:true})}
  if(savedProfile&&req.method==="DELETE"){await sql.run("DELETE FROM saved_profiles WHERE user_id=? AND saved_user_id=?",u.id,savedProfile[1]);return json(res,200,{ok:true})}
  if(url.pathname==="/api/conversations"&&req.method==="POST"){const d=await body(req),members=[...new Set([u.id,...(Array.isArray(d.memberIds)?d.memberIds:[])])];for(const member of members){if(!await sql.one("SELECT 1 FROM users WHERE id=?",member))return json(res,400,{error:"Conversation member is invalid"});if(member!==u.id&&await sql.one("SELECT 1 FROM user_blocks WHERE (blocker_id=? AND blocked_id=?) OR (blocker_id=? AND blocked_id=?)",u.id,member,member,u.id))return json(res,403,{error:"Conversation cannot be created"})}const id=randomUUID();await sql.transaction(async tx=>{await tx.run("INSERT INTO conversations(id,kind,title,created_by) VALUES(?,?,?,?)",id,d.kind||"private",d.title,u.id);for(const member of members)await tx.run("INSERT INTO conversation_members(conversation_id,user_id) VALUES(?,?)",id,member)});return json(res,201,{id})}
  if(url.pathname==="/api/conversations"&&req.method==="GET"){const page=pageParams(url);const rows=await sql.all(`SELECT c.*,cm.last_read_at,cm.blocked_at,(SELECT body FROM messages WHERE conversation_id=c.id ORDER BY created_at DESC LIMIT 1) last_message FROM conversations c JOIN conversation_members cm ON cm.conversation_id=c.id WHERE cm.user_id=? ORDER BY c.created_at DESC LIMIT ? OFFSET ?`,u.id,page.limit,page.cursor);return json(res,200,{conversations:rows,nextCursor:page.next(rows)})}
  const msgMatch=url.pathname.match(/^\/api\/conversations\/([^/]+)\/messages$/);if(msgMatch&&req.method==="GET"){const member=await sql.one("SELECT 1 FROM conversation_members WHERE conversation_id=? AND user_id=?",msgMatch[1],u.id);if(!member)return json(res,403,{error:"Forbidden"});const page=pageParams(url,{defaultLimit:50,maxLimit:100}),rows=await sql.all("SELECT * FROM messages WHERE conversation_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?",msgMatch[1],page.limit,page.cursor);return json(res,200,{messages:rows.reverse(),nextCursor:page.next(rows)})}
  if(msgMatch&&req.method==="POST"){const member=await sql.one("SELECT blocked_at FROM conversation_members WHERE conversation_id=? AND user_id=?",msgMatch[1],u.id);if(!member||member.blocked_at)return json(res,403,{error:"Conversation unavailable"});const route=`/api/conversations/${msgMatch[1]}/messages`,key=idempotencyKey(req);if(await idempotencyReplay(u.id,key,route,res))return;const d=await body(req),messageBody=String(d.body||"").trim();if(messageBody.length<1||messageBody.length>5000)return json(res,400,{error:"Message must be between 1 and 5000 characters"});const risk=await fraudSignal(messageBody),id=randomUUID(),result={id,risk},expires=new Date(Date.now()+24*60*60_000).toISOString();try{await sql.transaction(async tx=>{await tx.run("INSERT INTO messages(id,conversation_id,sender_id,body,attachment_key,risk_score) VALUES(?,?,?,?,?,?)",id,msgMatch[1],u.id,messageBody,d.attachmentKey,risk.score);if(key)await tx.run("INSERT INTO idempotency_keys(user_id,key,route,status,response,expires_at) VALUES(?,?,?,?,?,?)",u.id,key,route,201,JSON.stringify(result),expires)})}catch(error){if(await idempotencyReplay(u.id,key,route,res))return;throw error}const recipients=await sql.all("SELECT user_id FROM conversation_members WHERE conversation_id=? AND user_id<>? AND blocked_at IS NULL",msgMatch[1],u.id);for(const r of recipients){await notify(r.user_id,"message",`New message from ${u.name}`,risk.score>=.5?"Potential payment risk detected":messageBody);await publishUser(r.user_id,"message",{id,conversationId:msgMatch[1],senderId:u.id,body:messageBody,risk})}return json(res,201,result)}
  const blockMatch=url.pathname.match(/^\/api\/conversations\/([^/]+)\/block$/);if(blockMatch&&req.method==="POST"){await sql.run("UPDATE conversation_members SET blocked_at=CURRENT_TIMESTAMP WHERE conversation_id=? AND user_id=?",blockMatch[1],u.id);return json(res,200,{ok:true})}
  if(blockMatch&&req.method==="DELETE"){await sql.run("UPDATE conversation_members SET blocked_at=NULL WHERE conversation_id=? AND user_id=?",blockMatch[1],u.id);return json(res,200,{ok:true})}
  if(url.pathname==="/api/reports"&&req.method==="POST"){const d=await body(req),details=String(d.details||"").trim(),targetId=String(d.targetId||"").trim();if(!["user","listing","message","general"].includes(d.targetType)||targetId.length<1||targetId.length>100||details.length<20||details.length>5000)return json(res,400,{error:"Valid report target and details are required"});const id=randomUUID(),risk=["low","medium","high","critical"].includes(d.risk)?d.risk:"medium";await sql.run("INSERT INTO reports(id,reporter_id,target_type,target_id,category,details,risk) VALUES(?,?,?,?,?,?,?)",id,u.id,d.targetType,targetId,String(d.category||"other").slice(0,100),details,risk);await audit(req,"safety.report",{actorId:u.id,targetType:d.targetType,targetId,metadata:{reportId:id,category:d.category,risk}});return json(res,201,{id,status:"new"})}
  if(url.pathname==="/api/verifications"&&req.method==="POST"){const d=await body(req);if(!["identity","institution","listing"].includes(d.subjectType))return json(res,400,{error:"Invalid verification type"});if(d.subjectType==="listing"&&!await sql.one("SELECT 1 FROM listings WHERE id=? AND owner_id=?",d.subjectId,u.id))return json(res,403,{error:"Only the listing owner may request verification"});const id=randomUUID();await sql.run("INSERT INTO verification_requests(id,user_id,subject_type,subject_id,document_key) VALUES(?,?,?,?,?)",id,u.id,d.subjectType,d.subjectId,d.documentKey);return json(res,201,{id,status:"pending",privacy:"Documents remain private and are never added to public profiles"})}
  if(url.pathname==="/api/verifications"&&req.method==="GET")return json(res,200,{requests:await sql.all("SELECT id,subject_type,subject_id,status,decision_reason,created_at,reviewed_at FROM verification_requests WHERE user_id=? ORDER BY created_at DESC",u.id)});
  if(url.pathname==="/api/households"&&req.method==="POST"){const d=await body(req),id=randomUUID();await sql.transaction(async tx=>{await tx.run("INSERT INTO households(id,name,created_by) VALUES(?,?,?)",id,d.name,u.id);await tx.run("INSERT INTO household_members(household_id,user_id,role) VALUES(?,?,?)",id,u.id,"owner")});await audit(req,"household.create",{actorId:u.id,targetType:"household",targetId:id});return json(res,201,{id})}
  if(url.pathname==="/api/households"&&req.method==="GET"){const rows=await sql.all("SELECT h.*,hm.role,hm.room_name,hm.rent_share FROM households h JOIN household_members hm ON hm.household_id=h.id WHERE hm.user_id=? ORDER BY h.created_at DESC",u.id);return json(res,200,{households:rows})}
  const householdDetail=url.pathname.match(/^\/api\/households\/([^/]+)$/);if(householdDetail&&req.method==="GET"){const membership=await sql.one("SELECT 1 FROM household_members WHERE household_id=? AND user_id=?",householdDetail[1],u.id);if(!membership)return json(res,403,{error:"Forbidden"});const household=await sql.one("SELECT * FROM households WHERE id=?",householdDetail[1]),members=await sql.all("SELECT hm.*,u.name FROM household_members hm JOIN users u ON u.id=hm.user_id WHERE hm.household_id=?",householdDetail[1]),shortlist=await sql.all("SELECT hl.*,l.title,l.rent,l.city FROM household_listings hl JOIN listings l ON l.id=hl.listing_id WHERE hl.household_id=?",householdDetail[1]);return json(res,200,{household,members,shortlist})}
  if(householdDetail&&req.method==="PATCH"){if(!await canManageHousehold(u.id,householdDetail[1]))return json(res,403,{error:"Only the household owner can update this household"});const d=await body(req);if(d.name)await sql.run("UPDATE households SET name=? WHERE id=?",String(d.name).trim().slice(0,100),householdDetail[1]);return json(res,200,{ok:true})}
  const householdMatch=url.pathname.match(/^\/api\/households\/([^/]+)\/members$/);if(householdMatch&&req.method==="POST"){if(!await canManageHousehold(u.id,householdMatch[1]))return json(res,403,{error:"Only the household owner can manage members"});const d=await body(req);await sql.run("INSERT INTO household_members(household_id,user_id) VALUES(?,?) ON CONFLICT DO NOTHING",householdMatch[1],d.userId);await audit(req,"household.member_add",{actorId:u.id,targetType:"household",targetId:householdMatch[1],metadata:{memberId:d.userId}});return json(res,200,{ok:true})}
  const householdMember=url.pathname.match(/^\/api\/households\/([^/]+)\/members\/([^/]+)$/);if(householdMember&&req.method==="DELETE"){if(!await canManageHousehold(u.id,householdMember[1]))return json(res,403,{error:"Only the household owner can manage members"});await sql.run("DELETE FROM household_members WHERE household_id=? AND user_id=? AND role<>'owner'",householdMember[1],householdMember[2]);return json(res,200,{ok:true})}
  if(url.pathname==="/api/lease-workflows"&&req.method==="POST"){const d=await body(req);if(!await canManageListing(u.id,d.listingId))return json(res,403,{error:"Only the listing owner can create a lease workflow"});const id=randomUUID();await sql.run("INSERT INTO lease_workflows(id,listing_id,outgoing_user_id,incoming_user_id,transfer_type,replacement_date,fee,landlord_status,steps) VALUES(?,?,?,?,?,?,?,?,?)",id,d.listingId,u.id,d.incomingUserId,d.transferType,d.replacementDate,d.fee,d.landlordStatus||"not_contacted",JSON.stringify(d.steps||{}));return json(res,201,{id})}
  if(url.pathname==="/api/lease-workflows"&&req.method==="GET"){const rows=await sql.all("SELECT lw.* FROM lease_workflows lw WHERE lw.outgoing_user_id=? OR lw.incoming_user_id=? ORDER BY lw.created_at DESC",u.id,u.id);return json(res,200,{workflows:rows.map(x=>({...x,steps:typeof x.steps==="string"?JSON.parse(x.steps||"{}"):x.steps||{}}))})}
  const leaseMatch=url.pathname.match(/^\/api\/lease-workflows\/([^/]+)$/);if(leaseMatch&&req.method==="PATCH"){const workflow=await sql.one("SELECT * FROM lease_workflows WHERE id=?",leaseMatch[1]);if(!workflow||workflow.outgoing_user_id!==u.id)return json(res,403,{error:"Only the outgoing tenant can update this workflow"});const d=await body(req);await sql.run("UPDATE lease_workflows SET replacement_date=?,fee=?,landlord_status=?,steps=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",d.replacementDate,Number(d.fee)||0,d.landlordStatus,JSON.stringify(d.steps||{}),leaseMatch[1]);return json(res,200,{ok:true})}
  if(url.pathname==="/api/admin/reports"&&req.method==="GET"){if(!await requireAnyRole(u,res,["moderator","admin"]))return;return json(res,200,{reports:await sql.all("SELECT * FROM reports ORDER BY created_at DESC LIMIT 100")})}
  const reportDecision=url.pathname.match(/^\/api\/admin\/reports\/([^/]+)$/);if(reportDecision&&req.method==="PATCH"){if(!await requireAnyRole(u,res,["moderator","admin"]))return;const d=await body(req),reason=String(d.reason||"").trim();if(!["reviewing","resolved","dismissed","escalated"].includes(d.status)||reason.length<5)return json(res,400,{error:"Valid report status and reason are required"});await sql.transaction(async tx=>{await tx.run("UPDATE reports SET status=?,assigned_to=? WHERE id=?",d.status,u.id,reportDecision[1]);await tx.run("INSERT INTO moderation_actions(id,moderator_id,action,target_type,target_id,reason,metadata) VALUES(?,?,?,?,?,?,?)",randomUUID(),u.id,`report.${d.status}`,"report",reportDecision[1],reason,JSON.stringify({}))});await audit(req,"moderation.report_update",{actorId:u.id,targetType:"report",targetId:reportDecision[1],metadata:{status:d.status,reason}});return json(res,200,{ok:true})}
  if(url.pathname==="/api/admin/queue"&&req.method==="GET"){if(!await requireAnyRole(u,res,["moderator","admin"]))return;const [reports,listings,verifications,appeals,uploads]=await Promise.all([sql.all("SELECT * FROM reports WHERE status IN ('new','reviewing','escalated') ORDER BY created_at LIMIT 100"),sql.all("SELECT id,owner_id,title,city,status,created_at FROM listings WHERE status='pending_review' ORDER BY created_at LIMIT 100"),sql.all("SELECT * FROM verification_requests WHERE status='pending' ORDER BY created_at LIMIT 100"),sql.all("SELECT * FROM moderation_appeals WHERE status='pending' ORDER BY created_at LIMIT 100"),sql.all("SELECT id,user_id,purpose,filename,content_type,byte_size,status,created_at FROM upload_intents WHERE status IN ('quarantined','rejected') ORDER BY created_at LIMIT 100")]);return json(res,200,{reports,listings,verifications,appeals,uploads})}
  const listingDecision=url.pathname.match(/^\/api\/admin\/listings\/([^/]+)$/);if(listingDecision&&req.method==="PATCH"){if(!await requireAnyRole(u,res,["moderator","admin"]))return;const d=await body(req),reason=String(d.reason||"").trim();if(!["active","rejected","removed"].includes(d.status)||reason.length<5)return json(res,400,{error:"Status and decision reason are required"});await sql.transaction(async tx=>{await tx.run("UPDATE listings SET status=? WHERE id=?",d.status,listingDecision[1]);await tx.run("INSERT INTO moderation_actions(id,moderator_id,action,target_type,target_id,reason,metadata) VALUES(?,?,?,?,?,?,?)",randomUUID(),u.id,`listing.${d.status}`,"listing",listingDecision[1],reason,JSON.stringify({}))});await cacheDeletePrefix("listings:");return json(res,200,{ok:true})}
  const verificationDecision=url.pathname.match(/^\/api\/admin\/verifications\/([^/]+)$/);if(verificationDecision&&req.method==="PATCH"){if(!await requireAnyRole(u,res,["moderator","admin"]))return;const d=await body(req),reason=String(d.reason||"").trim(),request=await sql.one("SELECT * FROM verification_requests WHERE id=?",verificationDecision[1]);if(!request||!["approved","rejected"].includes(d.status)||reason.length<5)return json(res,400,{error:"Valid status and reason are required"});await sql.transaction(async tx=>{await tx.run("UPDATE verification_requests SET status=?,reviewer_id=?,decision_reason=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=?",d.status,u.id,reason,request.id);if(d.status==="approved"&&request.subject_type==="institution")await tx.run("UPDATE users SET institution_verified=1 WHERE id=?",request.user_id);if(d.status==="approved"&&request.subject_type==="listing")await tx.run("UPDATE listings SET verification_status='verified' WHERE id=?",request.subject_id);await tx.run("INSERT INTO moderation_actions(id,moderator_id,action,target_type,target_id,reason,metadata) VALUES(?,?,?,?,?,?,?)",randomUUID(),u.id,`verification.${d.status}`,"verification",request.id,reason,JSON.stringify({}))});return json(res,200,{ok:true})}
  const userEnforcement=url.pathname.match(/^\/api\/admin\/users\/([^/]+)\/enforcements$/);if(userEnforcement&&req.method==="POST"){if(!await requireAnyRole(u,res,["moderator","admin"]))return;const d=await body(req),reason=String(d.reason||"").trim();if(!["warning","suspension","ban"].includes(d.action)||reason.length<10)return json(res,400,{error:"Valid action and detailed reason are required"});if(!await sql.one("SELECT 1 FROM users WHERE id=?",userEnforcement[1]))return json(res,404,{error:"User not found"});const expires=d.action==="suspension"&&d.expiresAt?new Date(d.expiresAt).toISOString():null,id=randomUUID();await sql.transaction(async tx=>{await tx.run("INSERT INTO user_enforcements(id,user_id,action,reason,expires_at,created_by) VALUES(?,?,?,?,?,?)",id,userEnforcement[1],d.action,reason,expires,u.id);if(d.action!=="warning")await tx.run("DELETE FROM sessions WHERE user_id=?",userEnforcement[1]);await tx.run("INSERT INTO moderation_actions(id,moderator_id,action,target_type,target_id,reason,metadata) VALUES(?,?,?,?,?,?,?)",randomUUID(),u.id,`user.${d.action}`,"user",userEnforcement[1],reason,JSON.stringify({enforcementId:id,expiresAt:expires}))});return json(res,201,{id})}
  const appealDecision=url.pathname.match(/^\/api\/admin\/appeals\/([^/]+)$/);if(appealDecision&&req.method==="PATCH"){if(!await requireAnyRole(u,res,["moderator","admin"]))return;const d=await body(req),reason=String(d.reason||"").trim(),appeal=await sql.one("SELECT * FROM moderation_appeals WHERE id=? AND status='pending'",appealDecision[1]);if(!appeal||!["approved","denied"].includes(d.status)||reason.length<10)return json(res,400,{error:"Valid decision and detailed reason are required"});await sql.transaction(async tx=>{await tx.run("UPDATE moderation_appeals SET status=?,reviewed_by=?,decision_reason=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=?",d.status,u.id,reason,appeal.id);if(d.status==="approved")await tx.run("UPDATE user_enforcements SET revoked_at=CURRENT_TIMESTAMP,revoked_by=? WHERE id=?",u.id,appeal.enforcement_id);await tx.run("INSERT INTO moderation_actions(id,moderator_id,action,target_type,target_id,reason,metadata) VALUES(?,?,?,?,?,?,?)",randomUUID(),u.id,`appeal.${d.status}`,"appeal",appeal.id,reason,JSON.stringify({enforcementId:appeal.enforcement_id}))});return json(res,200,{ok:true})}
  if(url.pathname==="/api/commute"&&req.method==="GET")return json(res,200,await commuteEstimate(url.searchParams.get("from")||"",url.searchParams.get("to")||""));
  if(url.pathname==="/api/notifications"&&req.method==="GET")return json(res,200,{notifications:await sql.all("SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 100",u.id)});
  if(url.pathname==="/api/ai/translate"&&req.method==="POST"){const d=await body(req);return json(res,200,await translate(d.text,d.targetLanguage))}
  if(url.pathname==="/api/ai/fraud-check"&&req.method==="POST"){const d=await body(req);return json(res,200,await fraudSignal(d.text))}
  return json(res,404,{error:"API route not found"});
}

function staticFile(req,res,url){let path=url.pathname==="/"?"/index.html":decodeURIComponent(url.pathname);const file=resolve(root,`.${path}`);if(!file.startsWith(root+sep)||!existsSync(file)||!statSync(file).isFile())return json(res,404,{error:"Not found"});res.writeHead(200,{"Content-Type":mime[extname(file)]||"application/octet-stream","Cache-Control":path.endsWith(".html")?"no-cache":"public, max-age=3600"});res.end(req.method==="HEAD"?undefined:readFileSync(file))}
const server=http.createServer(async(req,res)=>{
  const requestId=String(req.headers["x-request-id"]||requestUuid());observeRequest(req,res,requestId);res.setHeader("X-Request-Id",requestId);res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("Referrer-Policy","same-origin");res.setHeader("X-Frame-Options","DENY");res.setHeader("Cross-Origin-Opener-Policy","same-origin");res.setHeader("Cross-Origin-Resource-Policy","same-origin");if(config.production)res.setHeader("Strict-Transport-Security","max-age=31536000; includeSubDomains");res.setHeader("Permissions-Policy","camera=(), microphone=(), geolocation=(self)");res.setHeader("Content-Security-Policy","default-src 'self'; img-src 'self' data: https:; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'");
  const url=new URL(req.url,`http://${req.headers.host||"localhost"}`);
  try{if(url.pathname==="/internal/metrics"){if(!process.env.METRICS_TOKEN||req.headers.authorization!==`Bearer ${process.env.METRICS_TOKEN}`)return json(res,404,{error:"Not found"});res.writeHead(200,{"Content-Type":"text/plain; version=0.0.4"});return res.end(metrics())}if(["POST","PUT","PATCH","DELETE"].includes(req.method||"")&&req.headers.origin&&req.headers.origin!==config.publicOrigin)return json(res,403,{error:"Request origin is not allowed",code:"origin_rejected"});if(url.pathname.startsWith("/api/"))await api(req,res,url);else if(req.method==="GET"||req.method==="HEAD")staticFile(req,res,url);else json(res,405,{error:"Method not allowed"})}catch(error){if(error instanceof ValidationError&&!res.headersSent)return json(res,400,{error:error.message,code:"validation_error",fields:error.fields});console.error(JSON.stringify({level:"error",requestId,message:error.message,stack:error.stack}));if(!res.headersSent)json(res,500,{error:"Internal server error",requestId});else res.end()}
});
server.listen(config.port,config.host,()=>console.log(JSON.stringify({level:"info",message:"server_started",url:`http://${config.host}:${config.port}`})));
