// Server APIs are authoritative; browser storage is limited to non-sensitive display preferences.
const sessionUser = JSON.parse(sessionStorage.getItem("rbSession") || "null");
const state = {
  screen: sessionUser ? "dashboard" : "auth",
  authMode: "signup",
  pendingAuth: null,
  step: 1,
  matchView: "people",
  matches: [],
  discovery: "roommates",
  listingView: "grid",
  listingCategory: "All homes",
  listings: [],
  commuteTo: "NYU",
  appSection: "discover",
  searchFilters: {budget:2600,location:"All locations",moveBy:"",roomType:"All types",lease:"Any lease",maxCommute:60},
  savedSearches: [],
  alertsEnabled: false,
  conversations: [],
  household: null,
  language: "English",
  currency: "USD",
  lifeTab: "safety",
  filter: "All matches",
  feedback: {},
  saved: [],
  user: sessionUser
};
const app = document.querySelector("#app");
const icon = (name) => ({ home:"⌂", spark:"✦", chat:"◌", shield:"✓", pin:"⌖", heart:"♡" }[name] || "•");
const escapeHtml = value => String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));

function render() {
  if (state.screen === "auth") renderAuth();
  else if (state.screen === "onboard") renderOnboard();
  else if(state.appSection==="messages") renderMessages();
  else if(state.appSection==="household") renderHousehold();
  else if(state.appSection==="life") renderLifeHub();
  else renderDashboard();
}

function brand() { return `<div class="brand"><span class="brand-mark">⌂</span> RoomBridge</div>`; }
function mainNav(active) { return `<nav class="nav"><button class="${active==='roommates'?'active':''}" id="roommateNav">${icon('spark')} Roommates</button><button class="${active==='housing'?'active':''}" id="housingNav">⌂ Housing</button><button class="${active==='messages'?'active':''}" id="messagesNav">${icon('chat')} Messages</button><button class="${active==='household'?'active':''}" id="householdNav">♧ Household</button><button class="${active==='life'?'active':''}" id="lifeNav">◎ Life hub</button></nav>`; }
function bindMainNav(){document.querySelector('#roommateNav')?.addEventListener('click',()=>{state.appSection='discover';state.discovery='roommates';renderDashboard()});document.querySelector('#housingNav')?.addEventListener('click',()=>{state.appSection='discover';state.discovery='housing';renderListings()});document.querySelector('#messagesNav')?.addEventListener('click',()=>{state.appSection='messages';renderMessages()});document.querySelector('#householdNav')?.addEventListener('click',()=>{state.appSection='household';renderHousehold()});document.querySelector('#lifeNav')?.addEventListener('click',()=>{state.appSection='life';renderLifeHub()});document.querySelector('#securityCenter')?.addEventListener('click',openSecurityCenter)}

function authLayout(card) {
  return `<main class="hero">${brand()}<section class="hero-copy"><span class="eyebrow">Built for life abroad</span><h1>Find your people.<br>Feel at home.</h1><p>Compatible roommates and trusted housing for international students and professionals—matched around the things that make living together work.</p><div class="trust-row"><span><b>✓</b> Verified community</span><span><b>✓</b> Secure sign-in</span><span><b>✓</b> Privacy first</span></div></section><section class="auth-wrap">${card}</section></main>`;
}

function renderAuth() {
  if (state.authMode === "verify") return renderVerification();
  if (state.authMode === "forgot") return renderForgotPassword();
  if (state.authMode === "reset") return renderResetPassword();
  const signup = state.authMode === "signup";
  app.innerHTML = `<main class="hero">
    ${brand()}
    <section class="hero-copy">
      <span class="eyebrow">Built for life abroad</span>
      <h1>Find your people.<br>Feel at home.</h1>
      <p>Compatible roommates and trusted housing for international students and professionals—matched around the things that make living together work.</p>
      <div class="trust-row"><span><b>✓</b> Compatibility matching</span><span><b>✓</b> Community focused</span><span><b>✓</b> Privacy first</span></div>
    </section>
    <section class="auth-wrap">
      <form class="auth-card" id="authForm">
        <div class="auth-tabs"><button type="button" class="${signup?'active':''}" data-mode="signup">Sign up</button><button type="button" class="${!signup?'active':''}" data-mode="signin">Sign in</button></div>
        <h2>${signup?'Create your account':'Welcome back'}</h2><p class="subtext">${signup?'Your next home starts with the right connection.':'Sign in to continue finding your people.'}</p>
        <div class="fields">
          ${signup?'<label>Full name<input name="name" required placeholder="Your full name" autocomplete="name"></label>':''}
          <label>Email address<input name="email" required type="email" placeholder="you@example.com" autocomplete="email"></label>
          <label>Password<div class="password-wrap"><input name="password" required type="password" minlength="12" placeholder="At least 12 characters" autocomplete="${signup?'new-password':'current-password'}"><button type="button" class="show-password" aria-label="Show password">Show</button></div></label>
          ${signup?'<div class="password-rules"><span>Use 12+ characters with a number and a letter.</span></div>':'<button type="button" class="text-btn" id="forgot">Forgot password?</button>'}
        </div>
        <p class="auth-error" id="authError" role="alert"></p>
        <button class="btn btn-primary btn-wide">${signup?'Create account':'Sign in'} <span>→</span></button>
        <p class="fine">By continuing, you agree to our <a href="/community-guidelines.html">community guidelines</a>, <a href="/terms.html">terms</a>, and <a href="/privacy.html">privacy notice</a>.</p>
      </form>
    </section>
  </main>`;
  document.querySelectorAll("[data-mode]").forEach(b => b.onclick = () => { state.authMode=b.dataset.mode; render(); });
  document.querySelector(".show-password").onclick = e => { const input=e.target.previousElementSibling; input.type=input.type==="password"?"text":"password"; e.target.textContent=input.type==="password"?"Show":"Hide"; };
  document.querySelector("#forgot")?.addEventListener("click", () => { state.authMode="forgot"; render(); });
  document.querySelector("#authForm").addEventListener("submit", async e => {
    e.preventDefault();
    const data = Object.fromEntries(new FormData(e.target));
    const error = document.querySelector("#authError");
    const email=data.email.trim().toLowerCase();
    if (signup) {
      if (!/(?=.*[A-Za-z])(?=.*\d).{12,}/.test(data.password)) { error.textContent="Use at least 12 characters, including a letter and a number."; return; }
      try { const result=await RoomBridgeAPI.register({name:data.name.trim(),email,password:data.password});state.pendingAuth={type:"email",accountId:result.userId,destination:email,code:result.demoCode,verificationId:result.verificationId,server:true};state.authMode="verify";render() } catch(apiError) { error.textContent=apiError.message; }
    } else {
      try { const result=await RoomBridgeAPI.login({email,password:data.password});state.user=result.user;sessionStorage.setItem("rbSession",JSON.stringify(state.user));const profile=(await RoomBridgeAPI.profile()).profile;if(profile)state.user={...state.user,...profile};state.screen=profile?"dashboard":"onboard";render() } catch(apiError) { error.textContent=apiError.message; }
    }
  });
}

function renderVerification() {
  const p=state.pendingAuth;
  if (!p) { state.authMode="signup"; return render(); }
  const label=p.type==="phone"?"phone number":"email address";
  app.innerHTML=authLayout(`<form class="auth-card" id="verifyForm"><button type="button" class="back-link" id="authBack">← Back</button><div class="verify-icon">${p.type==="phone"?'◫':'✉'}</div><h2>Verify your ${escapeHtml(p.type)}</h2><p class="subtext">We sent a 6-digit code to <strong>${escapeHtml(p.destination)}</strong>.</p>${p.code?`<div class="demo-code"><span>Development verification code</span><strong>${escapeHtml(p.code)}</strong></div>`:""}<label>Verification code<input class="otp-input" name="code" required inputmode="numeric" maxlength="6" pattern="[0-9]{6}" placeholder="000000" autocomplete="one-time-code"></label><p class="auth-error" id="authError"></p><button class="btn btn-primary btn-wide">Verify and continue</button><button type="button" class="text-btn resend" id="resend">Resend code</button></form>`);
  document.querySelector("#authBack").onclick=()=>{state.authMode="signup";state.pendingAuth=null;render()};
  document.querySelector("#resend").onclick=async()=>{try{const result=await RoomBridgeAPI.resendCode(p.verificationId);p.verificationId=result.verificationId;p.code=result.demoCode;render();showToast("A new verification code was sent")}catch(error){showToast(error.message)}};
  document.querySelector("#verifyForm").onsubmit=async e=>{e.preventDefault();const code=new FormData(e.target).get("code"),error=document.querySelector("#authError");try{const result=await RoomBridgeAPI.verify({verificationId:p.verificationId,code});state.user=result.user;sessionStorage.setItem("rbSession",JSON.stringify(state.user));state.pendingAuth=null;state.screen="onboard";render();showToast(`${p.type==='email'?'Email':'Phone'} verified successfully`)}catch(apiError){error.textContent=apiError.message}};
}

function renderForgotPassword() {
  app.innerHTML=authLayout(`<form class="auth-card" id="forgotForm"><button type="button" class="back-link" id="authBack">← Back to sign in</button><div class="verify-icon">↻</div><h2>Reset your password</h2><p class="subtext">Enter your account email and we'll send a reset code.</p><label>Email address<input name="email" required type="email" placeholder="you@example.com"></label><p class="auth-error" id="authError"></p><button class="btn btn-primary btn-wide">Send reset code</button></form>`);
  document.querySelector("#authBack").onclick=()=>{state.authMode="signin";render()};
  document.querySelector("#forgotForm").onsubmit=async e=>{e.preventDefault();const email=new FormData(e.target).get("email").trim().toLowerCase(),error=document.querySelector("#authError");try{const result=await RoomBridgeAPI.requestPasswordReset(email);state.pendingAuth={type:"reset",destination:email,code:result.demoCode||"",verificationId:result.verificationId,server:true};state.authMode="reset";render()}catch(apiError){error.textContent=apiError.message}};
}

function renderResetPassword() {
  const p=state.pendingAuth;if(!p){state.authMode="signin";return render()}
  app.innerHTML=authLayout(`<form class="auth-card" id="resetForm"><button type="button" class="back-link" id="authBack">← Cancel</button><h2>Choose a new password</h2><p class="subtext">Enter the code and a strong new password.</p>${p.code?`<div class="demo-code"><span>Development reset code</span><strong>${escapeHtml(p.code)}</strong></div>`:""}<div class="fields"><label>Reset code<input name="code" required maxlength="6" inputmode="numeric" placeholder="000000"></label><label>New password<input name="password" required type="password" minlength="12" placeholder="12+ characters with a number"></label></div><p class="auth-error" id="authError"></p><button class="btn btn-primary btn-wide">Update password</button></form>`);
  document.querySelector("#authBack").onclick=()=>{state.pendingAuth=null;state.authMode="signin";render()};
  document.querySelector("#resetForm").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),error=document.querySelector("#authError");if(!p.verificationId){error.textContent="Request a new reset code.";return}try{await RoomBridgeAPI.confirmPasswordReset({verificationId:p.verificationId,code:d.code,password:d.password});state.pendingAuth=null;state.authMode="signin";render();showToast("Password updated. You can now sign in.")}catch(apiError){error.textContent=apiError.message}};
}

function choices(name, items, selected) {
  return `<div class="choice-grid">${items.map(([value, desc]) => `<label class="choice ${selected===value?'selected':''}"><input type="radio" name="${name}" value="${value}" ${selected===value?'checked':''} required><strong>${value}</strong><small>${desc}</small></label>`).join("")}</div>`;
}

function optionList(values, selected) { return values.map(v=>`<option ${v===selected?'selected':''}>${v}</option>`).join(''); }
function importance(name, label, value="Nice to have") { return `<label>${label}<select name="${name}">${optionList(["Required","Important","Nice to have","Doesn't matter"],value)}</select></label>`; }

function renderOnboard() {
  const titles = ["What brings you here?", "Tell us what you need", "A little about you", "Build your compatibility profile"];
  let content = "";
  if (state.step === 1) content = `${choices("scenario", [["Find a new home","Find a place and roommates"],["Find a roommate","Share your current room"],["Fill an available room","Rent a room in your home"],["Find my replacement","Transfer my spot or lease"]], state.user.scenario)}`;
  if (state.step === 2) content = `<div class="grid-2">
      <label>Preferred location<input name="city" required value="${escapeHtml(state.user.city||'')}" placeholder="e.g. Jersey City, NJ"></label>
      <label>Monthly budget (USD)<input name="budget" required type="number" min="200" value="${escapeHtml(state.user.budget||'')}" placeholder="1200"></label>
      <label>Room preference<select name="room" required>${optionList(["Private room","Shared room","Either works"],state.user.room)}</select></label>
      <label>People you want to live with<select name="people" required>${optionList(["1","2","3","4+"],state.user.people)}</select></label>
      <label>Move-in date<input name="move" required type="date" value="${escapeHtml(state.user.move||'')}"></label>
      <label>Stay duration<select name="duration">${optionList(["12+ months","6–12 months","3–6 months","Flexible"],state.user.duration)}</select></label>
    </div>`;
  if (state.step === 3) content = `<div class="grid-2">
      <label>Immigration / work status<select name="status">${optionList(["International student","OPT","STEM OPT","H-1B","Other","Prefer not to say"],state.user.status)}</select></label>
      <label>Country<input name="country" required value="${escapeHtml(state.user.country||'')}" placeholder="Country you call home"></label>
      <label>Food preference<select name="diet">${optionList(["Vegetarian","Non-vegetarian","Vegan","Halal","No preference"],state.user.diet)}</select></label>
      <label>Languages<input name="languages" value="${escapeHtml(state.user.languages||'')}" placeholder="e.g. English, Hindi, Telugu"></label>
    </div><label style="margin-top:17px">Lifestyle & roommate preferences<textarea name="preferences" placeholder="Tell potential roommates about your schedule, cleanliness, pets, smoking, or anything important to you.">${escapeHtml(state.user.preferences||'')}</textarea></label>`;
  if (state.step === 4) content = `<div class="question-block"><h3>Your everyday lifestyle</h3><div class="grid-2">
      <label>Cleanliness<select name="cleanliness">${optionList(["Very tidy","Tidy","Relaxed"],state.user.cleanliness)}</select></label>
      <label>Daily schedule<select name="schedule">${optionList(["Early riser","Night owl","Flexible"],state.user.schedule)}</select></label>
      <label>Home atmosphere<select name="social">${optionList(["Quiet","Balanced","Social"],state.user.social)}</select></label>
      <label>Overnight guests<select name="guests">${optionList(["Rarely","Occasionally","Often"],state.user.guests)}</select></label>
    </div></div><div class="question-block"><h3>How important is compatibility?</h3><p>Required preferences act as hard filters. Others contribute to the match score.</p><div class="grid-2">${importance("cleanlinessWeight","Similar cleanliness",state.user.cleanlinessWeight)}${importance("scheduleWeight","Similar schedule",state.user.scheduleWeight)}${importance("socialWeight","Similar social style",state.user.socialWeight)}${importance("budgetWeight","Budget alignment",state.user.budgetWeight||"Important")}</div></div>
    <div class="question-block"><h3>Deal-breakers</h3><p>Profiles that conflict with these choices will not appear.</p><div class="deal-grid">
      <label class="check-row"><input type="checkbox" name="noSmoking" ${state.user.noSmoking?'checked':''}><span><strong>Smoke-free home</strong><small>No indoor smokers</small></span></label>
      <label class="check-row"><input type="checkbox" name="noPets" ${state.user.noPets?'checked':''}><span><strong>No pets</strong><small>Exclude pet-friendly homes</small></span></label>
      <label class="check-row"><input type="checkbox" name="dietRequired" ${state.user.dietRequired?'checked':''}><span><strong>Same food preference</strong><small>Diet must match mine</small></span></label>
      <label class="check-row"><input type="checkbox" name="rareGuests" ${state.user.rareGuests?'checked':''}><span><strong>Limited overnight guests</strong><small>Rarely or occasionally only</small></span></label>
    </div><label style="margin-top:15px">Gender preference<select name="genderPreference">${optionList(["No preference","Woman","Man","Non-binary"],state.user.genderPreference)}</select></label></div>`;
  app.innerHTML = `<main class="onboard">
    <aside class="onboard-aside">${brand()}<div class="steps">${[1,2,3,4].map((n,i)=>`<div class="step ${state.step===n?'active':''} ${state.step>n?'done':''}"><span class="step-num">${state.step>n?'✓':n}</span><div><strong>${["Your housing goal","Home preferences","About you","Compatibility"][i]}</strong><small>${["How can we help?","What works for you?","Introduce yourself","Priorities & deal-breakers"][i]}</small></div></div>`).join('')}</div></aside>
    <section class="onboard-main"><form class="form-card" id="profileForm">
      <div class="progress"><div style="width:${state.step*25}%"></div></div>
      <span class="eyebrow" style="color:var(--green)">Step ${state.step} of 4</span><h2>${titles[state.step-1]}</h2><p class="subtext">${["Choose the situation that best describes you.","These details help us find realistic, relevant matches.","Introduce yourself to potential roommates.","Tell us what makes sharing a home work for you."][state.step-1]}</p>
      ${content}
      <div class="actions">${state.step>1?'<button type="button" class="btn btn-ghost" id="back">← Back</button>':'<span></span>'}<button class="btn btn-primary">${state.step===4?'See my matches ✦':'Continue →'}</button></div>
    </form></section>
  </main>`;
  document.querySelectorAll(".choice").forEach(el => el.addEventListener("click", () => { document.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected")); el.classList.add("selected"); }));
  document.querySelector("#back")?.addEventListener("click", () => { state.step--; render(); });
  document.querySelector("#profileForm").addEventListener("submit", async e => {
    e.preventDefault(); const values=Object.fromEntries(new FormData(e.target)); if(state.step===4)["noSmoking","noPets","dietRequired","rareGuests"].forEach(k=>values[k]=new FormData(e.target).has(k)); Object.assign(state.user,values);
    if (state.step < 4) { state.step++; render(); }
    else { try{await RoomBridgeAPI.saveProfile({scenario:state.user.scenario,city:state.user.city,budget:Number(state.user.budget),roomType:state.user.room,moveDate:state.user.move,leaseDuration:state.user.duration,country:state.user.country,diet:state.user.diet,languages:(state.user.languages||"").split(/,\s*/),bio:state.user.preferences,lifestyle:{cleanliness:state.user.cleanliness,schedule:state.user.schedule,social:state.user.social,guests:state.user.guests},weights:{cleanliness:state.user.cleanlinessWeight,schedule:state.user.scheduleWeight,social:state.user.socialWeight,budget:state.user.budgetWeight},dealBreakers:{noSmoking:state.user.noSmoking,noPets:state.user.noPets,dietRequired:state.user.dietRequired,rareGuests:state.user.rareGuests}});state.screen="dashboard";render();showToast("Your profile is live — welcome to RoomBridge!")}catch(error){showToast(error.message)} }
  });
}

function scoreProfile(p) {
  const u=state.user||{}, conflicts=[];
  if(u.noSmoking&&p.smoking!=="No")conflicts.push("smoking conflicts with your deal-breaker");
  if(u.noPets&&p.pets!=="No pets")conflicts.push("pets conflict with your deal-breaker");
  if(u.dietRequired&&u.diet&&p.diet!==u.diet)conflicts.push("food preference must match");
  if(u.rareGuests&&p.guests==="Often")conflicts.push("overnight guest preference conflicts");
  if(u.genderPreference&&u.genderPreference!=="No preference"&&p.gender!==u.genderPreference)conflicts.push("gender preference does not match");
  const required={cleanlinessWeight:[u.cleanliness,p.cleanliness,"cleanliness"],scheduleWeight:[u.schedule,p.schedule,"schedule"],socialWeight:[u.social,p.social,"home atmosphere"]};
  Object.entries(required).forEach(([key,[a,b,label]])=>{if(u[key]==="Required"&&a&&a!==b)conflicts.push(`${label} is marked required`)});
  if(conflicts.length)return {excluded:true,conflicts,score:0,reasons:[],breakdown:[]};
  const weight=v=>({"Required":14,"Important":11,"Nice to have":6,"Doesn't matter":0}[v]??6);
  let earned=35, possible=35, breakdown=[];
  const add=(label,matched,w,detail)=>{possible+=w;if(matched)earned+=w;breakdown.push({label,matched,points:matched?w:0,max:w,detail})};
  const sameCity=!u.city||p.city.toLowerCase().includes(u.city.split(',')[0].toLowerCase());add("Location",sameCity,14,sameCity?"Preferred area matches":"Different nearby area");
  const budget=Number(u.budget)||1300,budgetClose=Math.abs(p.budget-budget)<=200;add("Budget",budgetClose,weight(u.budgetWeight||"Important"),budgetClose?"Within $200 of your budget":`$${Math.abs(p.budget-budget)} difference`);
  add("Room type",u.room===p.room||u.room==="Either works"||!u.room,8,u.room===p.room?"Same room preference":"Flexible or different");
  add("Cleanliness",!u.cleanliness||u.cleanliness===p.cleanliness,weight(u.cleanlinessWeight),`${p.cleanliness} lifestyle`);
  add("Schedule",!u.schedule||u.schedule===p.schedule,weight(u.scheduleWeight),p.schedule);
  add("Home atmosphere",!u.social||u.social===p.social,weight(u.socialWeight),p.social);
  add("Food preference",u.diet===p.diet||u.diet==="No preference"||!u.diet,7,p.diet);
  const langs=(u.languages||"").toLowerCase().split(/,\s*/).filter(Boolean),shared=p.languages.find(l=>langs.includes(l.toLowerCase()));add("Language",!!shared,5,shared?`Both speak ${shared}`:"No listed shared language");
  let score=Math.round(earned/possible*100);const feedback=state.feedback[p.id];if(feedback==="more")score+=4;if(feedback==="less")score-=8;
  const reasons=breakdown.filter(x=>x.matched&&x.max>0).sort((a,b)=>b.max-a.max).slice(0,3).map(x=>x.detail);
  return {excluded:false,score:Math.max(35,Math.min(score,98)),reasons,breakdown,conflicts:[]};
}

function buildGroups(profiles) {
  const eligible=profiles.filter(p=>!p.excluded).slice(0,6),groups=[];
  for(let a=0;a<eligible.length;a++)for(let b=a+1;b<eligible.length;b++)for(let c=b+1;c<eligible.length;c++){
    const members=[eligible[a],eligible[b],eligible[c]], cities=new Set(members.map(x=>x.city)), smoke=members.every(x=>x.smoking==="No"), clean=new Set(members.map(x=>x.cleanliness)).size<=2;
    let score=Math.round(members.reduce((s,x)=>s+x.score,0)/3)+(cities.size===1?4:0)+(smoke?2:0)+(clean?2:0);
    groups.push({id:members.map(x=>x.id).join('-'),members,score:Math.min(score,98),budget:members.reduce((s,x)=>s+x.budget,0),reasons:[cities.size===1?"same target area":"nearby locations",smoke?"smoke-free household":"compatible housing needs",clean?"similar cleanliness":"balanced lifestyles"]});
  }
  for(let a=0;a<eligible.length;a++)for(let b=a+1;b<eligible.length;b++)for(let c=b+1;c<eligible.length;c++)for(let d=c+1;d<eligible.length;d++){
    const members=[eligible[a],eligible[b],eligible[c],eligible[d]],cities=new Set(members.map(x=>x.city)),smoke=members.every(x=>x.smoking==="No"),clean=new Set(members.map(x=>x.cleanliness)).size<=2;
    let score=Math.round(members.reduce((s,x)=>s+x.score,0)/4)+(cities.size<=2?3:0)+(smoke?2:0)+(clean?2:0);
    groups.push({id:members.map(x=>x.id).join('-'),members,score:Math.min(score,98),budget:members.reduce((s,x)=>s+x.budget,0),reasons:[cities.size<=2?"close target areas":"compatible move plans",smoke?"smoke-free household":"shared housing goals",clean?"similar cleanliness":"balanced lifestyles"]});
  }
  return groups.sort((a,b)=>b.score-a.score).slice(0,4);
}

function roomIllustration(l, compact=false) {
  return `<svg class="room-art ${compact?'compact':''}" viewBox="0 0 600 330" role="img" aria-label="Illustration of ${escapeHtml(l.title)}"><rect width="600" height="330" fill="${l.color}"/><rect y="238" width="600" height="92" fill="${l.accent}" opacity=".16"/><rect x="55" y="42" width="175" height="145" rx="4" fill="#fff"/><rect x="69" y="56" width="147" height="117" fill="#cce5ed"/><path d="M142 56v117M69 114h147" stroke="#fff" stroke-width="8"/><circle cx="190" cy="82" r="22" fill="#fff3b0"/><rect x="285" y="170" width="245" height="84" rx="10" fill="#fff"/><rect x="303" y="146" width="80" height="48" rx="12" fill="#f8f3e8"/><rect x="398" y="151" width="105" height="44" rx="12" fill="${l.accent}" opacity=".42"/><rect x="270" y="250" width="275" height="12" rx="6" fill="${l.accent}"/><rect x="270" y="262" width="12" height="42" fill="${l.accent}"/><rect x="533" y="262" width="12" height="42" fill="${l.accent}"/><path d="M27 239h95v-80c0-34-23-59-48-59s-47 25-47 59z" fill="${l.accent}" opacity=".72"/><rect x="68" y="206" width="11" height="49" fill="#76563f"/></svg>`;
}
function listingShell(content) {
  return `<div class="shell"><header class="topbar">${brand()}${mainNav('housing')}<button class="avatar avatar-button" id="securityCenter" aria-label="Account and security">${(state.user.name||'RB').split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</button></header>${content}</div>`;
}
function renderListings() {
  const f=state.searchFilters, listings=state.listings.filter(l=>(state.listingCategory==="All homes"||l.category===state.listingCategory)&&l.rent<=f.budget&&(f.location==="All locations"||l.city.startsWith(f.location))&&(!f.moveBy||l.available<=f.moveBy)&&(f.roomType==="All types"||l.category===f.roomType)&&(f.lease==="Any lease"||l.lease.includes(f.lease))&&(l.commutes[state.commuteTo]??0)<=f.maxCommute);
  app.innerHTML=listingShell(`<main class="dashboard listings-page"><section class="listing-hero"><div><span class="eyebrow">Homes on RoomBridge</span><h1>Find a place that fits your life.</h1><p>Rooms, apartments, and verified lease transfers—with the details that matter before you visit.</p></div><button class="btn btn-primary" id="createListing">+ List a room</button></section><form class="advanced-search" id="searchFilters"><label>Max budget<input name="budget" type="number" value="${f.budget}" min="200"></label><label>Location<select name="location">${["All locations","Jersey City","Hoboken","Newark"].map(x=>`<option ${x===f.location?'selected':''}>${x}</option>`).join('')}</select></label><label>Move in by<input name="moveBy" type="date" value="${f.moveBy}"></label><label>Room type<select name="roomType">${["All types","Private room","Shared room","Entire apartment","Lease transfer"].map(x=>`<option ${x===f.roomType?'selected':''}>${x}</option>`).join('')}</select></label><label>Lease length<select name="lease">${["Any lease","6–12","12","Month-to-month"].map(x=>`<option ${x===f.lease?'selected':''}>${x}</option>`).join('')}</select></label><label>Max commute<select name="maxCommute">${[15,30,45,60,90].map(x=>`<option value="${x}" ${x==f.maxCommute?'selected':''}>${x} min</option>`).join('')}</select></label><button class="btn btn-primary">Search</button></form><div class="search-actions"><span><b>${listings.length}</b> suitable homes</span><button class="btn btn-ghost" id="saveSearch">☆ Save this search</button><button class="btn ${state.alertsEnabled?'btn-secondary':'btn-ghost'}" id="toggleAlerts">${state.alertsEnabled?'🔔 Alerts on':'♢ Get alerts'}</button>${state.savedSearches.length?`<span class="saved-count">${state.savedSearches.length} saved search${state.savedSearches.length>1?'es':''}</span>`:''}</div><section class="listing-toolbar"><div class="filters">${["All homes","Private room","Shared room","Entire apartment","Lease transfer"].map(x=>`<button type="button" class="filter ${state.listingCategory===x?'active':''}" data-category="${x}">${x}</button>`).join('')}</div><div class="view-toggle"><button type="button" class="${state.listingView==='grid'?'active':''}" data-list-view="grid">Grid</button><button type="button" class="${state.listingView==='map'?'active':''}" data-list-view="map">Map</button></div></section>${state.listingView==='map'?mapView(listings):`<div class="listing-grid">${listings.length?listings.map(listingCard).join(''):'<div class="empty">No homes match every filter. Try expanding your budget, date, or commute.</div>'}</div>`}</main>`);
  bindListingEvents();
}
function applyListingFilters(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));state.searchFilters={budget:Number(d.budget),location:d.location,moveBy:d.moveBy,roomType:d.roomType,lease:d.lease,maxCommute:Number(d.maxCommute)};renderListings()}
async function saveCurrentSearch(){try{const data={name:`${state.searchFilters.location} · under $${state.searchFilters.budget}`,filters:{...state.searchFilters},alertsEnabled:true},result=await RoomBridgeAPI.saveSearch(data);state.savedSearches.unshift({...data,id:result.id});state.alertsEnabled=true;renderListings();showToast('Search saved — alerts can notify you about new matches')}catch(error){showToast(error.message)}}
async function toggleAlerts(){const search=state.savedSearches[0];if(!search)return saveCurrentSearch();try{state.alertsEnabled=!state.alertsEnabled;await RoomBridgeAPI.updateSavedSearch(search.id,{alertsEnabled:state.alertsEnabled});search.alerts_enabled=state.alertsEnabled?1:0;renderListings();showToast(state.alertsEnabled?'New-match alerts enabled':'Search alerts paused')}catch(error){state.alertsEnabled=!state.alertsEnabled;showToast(error.message)}}
function listingCard(l) { const commute=l.commutes[state.commuteTo];return `<article class="listing-card"><div class="listing-media">${roomIllustration(l,true)}<span class="category-badge">${escapeHtml(l.category)}</span><span class="media-count">Media pending review</span></div><div class="listing-info"><div class="listing-title"><div><h3>${escapeHtml(l.title)}</h3><p>⌖ ${escapeHtml(l.area)} · ${escapeHtml(l.city)}</p></div><strong>$${l.rent.toLocaleString()}<small>/mo</small></strong></div><div class="listing-facts"><span>${l.beds} bed</span><span>${l.baths} bath</span><span>${escapeHtml(l.furnished)}</span><span>${escapeHtml(l.laundry)}</span></div><div class="availability"><span><b>Available</b>${l.available?new Date(l.available+'T12:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}):'Flexible'}</span><span><b>Lease</b>${escapeHtml(l.lease)}</span><span class="commute"><b>Commute</b>${commute||'—'} min to ${escapeHtml(state.commuteTo)}</span></div><button class="btn btn-primary btn-wide" data-listing="${escapeHtml(l.id)}">View home</button></div></article>`; }
function mapView(listings){return `<div class="map-layout"><aside class="map-results"><label>Estimate commute to<select id="commuteSelect">${["NYU","Columbia University","Google NYC","Newark Penn"].map(x=>`<option ${x===state.commuteTo?'selected':''}>${x}</option>`).join('')}</select></label>${listings.map(l=>`<button class="map-result" data-listing="${l.id}"><span>${l.category}</span><strong>${l.title}</strong><small>$${l.rent}/mo · ${l.commutes[state.commuteTo]} min commute</small></button>`).join('')}</aside><div class="map-canvas"><div class="river"></div><span class="map-label manhattan">MANHATTAN</span><span class="map-label jersey">NEW JERSEY</span>${listings.map(l=>`<button class="map-pin" style="left:${l.lat}%;top:${l.lng}%" data-listing="${l.id}">$${(l.rent/1000).toFixed(1)}k</button>`).join('')}<div class="map-legend">Approximate locations · commute estimates include transit</div></div></div>`}
function bindListingEvents(){bindMainNav();document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{state.listingCategory=b.dataset.category;renderListings()});document.querySelectorAll('[data-list-view]').forEach(b=>b.onclick=()=>{state.listingView=b.dataset.listView;renderListings()});document.querySelectorAll('[data-listing]').forEach(b=>b.onclick=()=>openListing(b.dataset.listing));document.querySelector('#commuteSelect')?.addEventListener('change',e=>{state.commuteTo=e.target.value;renderListings()});document.querySelector('#createListing').onclick=openCreateListing;document.querySelector('#saveSearch')?.addEventListener('click',saveCurrentSearch);document.querySelector('#toggleAlerts')?.addEventListener('click',toggleAlerts);document.querySelector('#searchFilters')?.addEventListener('submit',applyListingFilters)}
function openListing(id){const l=state.listings.find(x=>String(x.id)===String(id));if(!l)return;const modal=document.createElement('div');modal.className='modal-backdrop listing-backdrop';modal.innerHTML=`<div class="modal listing-modal"><div class="modal-head"><div><span class="eyebrow" style="color:var(--green)">${l.category}</span><h2>${l.title}</h2><p class="subtext">${l.area} · ${l.city}</p></div><button class="close">×</button></div><div class="media-tabs"><button class="active" data-media="photos">Photos</button><button data-media="video">Video ${l.video?'':'—'}</button><button data-media="floorplan">Floor plan</button></div><div id="mediaPanel">${mediaPanel(l,'photos')}</div><div class="listing-detail-head"><strong>$${l.rent.toLocaleString()}<small>/month</small></strong><span>Available ${l.available?new Date(l.available+'T12:00').toLocaleDateString():'Flexible'}</span></div><div class="detail-grid"><div><b>Deposit</b><span>$${l.deposit.toLocaleString()}</span></div><div><b>Lease duration</b><span>${l.lease}</span></div><div><b>Furnishing</b><span>${l.furnished}</span></div><div><b>Utilities</b><span>${l.utilities}</span></div><div><b>Parking</b><span>${l.parking}</span></div><div><b>Laundry</b><span>${l.laundry}</span></div><div><b>Accessibility</b><span>${l.accessibility}</span></div><div><b>Commute</b><span>${l.commutes[state.commuteTo]??'—'} min to ${state.commuteTo}</span></div></div><h3 class="amenity-title">Amenities</h3><div class="amenity-list">${l.amenities.map(a=>`<span>✓ ${a}</span>`).join('')}</div>${l.category==='Lease transfer'&&l.owner_id===state.user.id?'<button class="btn btn-secondary btn-wide" id="leaseWorkflow">Open lease replacement workflow</button>':''}<button class="btn btn-primary btn-wide" id="tourRequest">Request a tour</button></div>`;document.body.appendChild(modal);modal.querySelector('.close').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};modal.querySelectorAll('[data-media]').forEach(b=>b.onclick=()=>{modal.querySelectorAll('[data-media]').forEach(x=>x.classList.remove('active'));b.classList.add('active');modal.querySelector('#mediaPanel').innerHTML=mediaPanel(l,b.dataset.media)});modal.querySelector('#leaseWorkflow')?.addEventListener('click',()=>{modal.remove();openLeaseWorkflow(l.id)});modal.querySelector('#tourRequest').onclick=()=>{modal.remove();showToast('Tour request recorded')}}
function mediaPanel(l,type){if(type==='photos')return `<div class="photo-gallery">${roomIllustration(l)}<div>${roomIllustration({...l,color:'#eee5d7'})}${roomIllustration({...l,color:'#dce6e8'})}</div></div>`;if(type==='video')return l.video?`<div class="video-preview">${roomIllustration(l)}<button aria-label="Play home tour">▶</button><span>1:24 home tour</span></div>`:`<div class="media-empty">No video tour has been uploaded.</div>`;return `<div class="floor-plan"><div class="plan-room living">Living room</div><div class="plan-room bedroom">Bedroom</div><div class="plan-room kitchen">Kitchen</div><div class="plan-room bath">Bath</div><span>Illustrative floor plan · dimensions available from host</span></div>`}
function openCreateListing(){const modal=document.createElement('div');modal.className='modal-backdrop';modal.innerHTML=`<form class="modal" id="listingForm"><div class="modal-head"><div><span class="eyebrow" style="color:var(--green)">Host on RoomBridge</span><h2>List your space</h2></div><button type="button" class="close">×</button></div><p class="subtext">Media is uploaded privately and stays quarantined until scanning completes.</p><div class="grid-2"><label>Listing title<input required name="title" maxlength="120" placeholder="Bright room near transit"></label><label>Category<select name="category">${["Private room","Shared room","Entire apartment","Lease transfer"].map(x=>`<option>${x}</option>`).join('')}</select></label><label>City<input required name="city" maxlength="120" placeholder="Jersey City, NJ"></label><label>Neighborhood<input name="neighborhood" maxlength="120"></label><label>Monthly rent<input required name="rent" type="number" min="200" placeholder="1200"></label><label>Available from<input required name="availableDate" type="date"></label><label>Furnishing<select name="furnished"><option>Furnished</option><option>Unfurnished</option></select></label><label>Lease duration<select name="leaseDuration"><option>12 months</option><option>6–12 months</option><option>Month-to-month</option><option>Lease remainder</option></select></label></div><label>Description<textarea name="description" maxlength="2000"></textarea></label><label>Photos or video<input type="file" name="media" multiple accept="image/jpeg,image/png,image/webp,video/mp4"></label><button class="btn btn-primary btn-wide">Save draft listing</button></form>`;document.body.appendChild(modal);modal.querySelector('.close').onclick=()=>modal.remove();modal.querySelector('#listingForm').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target),files=form.getAll('media').filter(x=>x.size),data=Object.fromEntries(form);delete data.media;data.rent=Number(data.rent);try{const result=await RoomBridgeAPI.createListing(data);for(const file of files)await RoomBridgeAPI.uploadFile(file,'listing_media',result.id);modal.remove();showToast(files.length?'Listing saved; media is being scanned':'Draft listing saved and sent for review')}catch(error){showToast(error.message)}}}

function appShell(active,body){return `<div class="shell"><header class="topbar">${brand()}${mainNav(active)}<button class="avatar avatar-button" id="securityCenter">${(state.user.name||'RB').split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</button></header>${body}</div>`}
async function renderMessages(activeId){
  try{
    if(!state.conversations.length)state.conversations=(await RoomBridgeAPI.conversations()).conversations;
    if(!state.conversations.length){app.innerHTML=appShell('messages','<main class="dashboard"><div class="empty"><h2>No conversations yet</h2><p>Create a group when you are ready to plan with roommates.</p><button class="btn btn-primary" id="newGroup">Create conversation</button></div></main>');bindMainNav();document.querySelector('#newGroup').onclick=createGroupConversation;return}
    const active=state.conversations.find(c=>c.id===(activeId||state.conversations[0].id))||state.conversations[0];
    active.messages=(await RoomBridgeAPI.messages(active.id)).messages;
    const title=c=>c.title||'Conversation',initials=c=>title(c).split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();
    app.innerHTML=appShell('messages',`<main class="messenger"><aside class="conversation-list"><div class="conversation-title"><div><span class="eyebrow">Inbox</span><h1>Messages</h1></div><button class="new-chat" id="newGroup">+</button></div><div>${state.conversations.map(c=>`<button class="conversation-item ${c.id===active.id?'active':''}" data-conversation="${c.id}"><span class="conversation-avatar">${initials(c)}</span><span><strong>${escapeHtml(title(c))}</strong><small>${escapeHtml(c.last_message||'No messages yet')}</small></span></button>`).join('')}</div></aside><section class="chat"><header class="chat-head"><div><strong>${escapeHtml(title(active))}</strong><small>${escapeHtml(active.kind||'private')} conversation</small></div><button id="chatInfo" title="Conversation settings">•••</button></header><div class="message-thread"><div class="chat-safety">🛡 Never pay a deposit before verifying the home, host, and lease.</div>${active.blocked_at?'<div class="blocked-note">You blocked this conversation. Unblock to send messages.</div>':active.messages.map(m=>`<div class="bubble ${m.sender_id===state.user.id?'mine':''}"><p>${escapeHtml(m.body)}</p><span>${new Date(m.created_at).toLocaleString()}</span></div>`).join('')}</div><form class="composer" id="messageForm"><input name="message" maxlength="5000" placeholder="Write a message…" ${active.blocked_at?'disabled':''}><button ${active.blocked_at?'disabled':''}>Send</button></form></section></main>`);
    bindMainNav();document.querySelectorAll('[data-conversation]').forEach(b=>b.onclick=()=>renderMessages(b.dataset.conversation));document.querySelector('#newGroup').onclick=createGroupConversation;document.querySelector('#chatInfo').onclick=()=>openChatControls(active);document.querySelector('#messageForm').onsubmit=async e=>{e.preventDefault();const text=new FormData(e.target).get('message').trim();if(!text)return;const risk=scamRisk(text);if(risk.risky&&!confirm(`RoomBridge safety warning\n\n${risk.message}\n\nSend this message anyway?`))return;try{await RoomBridgeAPI.sendMessage(active.id,{body:text});await renderMessages(active.id)}catch(error){showToast(error.message)}};
  }catch(error){showToast(error.message)}
}
function startCall(type,c){const modal=document.createElement('div');modal.className='modal-backdrop call-screen';modal.innerHTML=`<div class="call-card"><span class="conversation-avatar large" style="background:${c.color}">${c.initials}</span><h2>${type==='video'?'Video':'Voice'} call with ${c.name}</h2><p>Connecting securely…</p><div><button>◉</button><button>♩</button><button class="end-call">End call</button></div></div>`;document.body.appendChild(modal);modal.querySelector('.end-call').onclick=()=>modal.remove()}
function openChatControls(c){const blocked=!!c.blocked_at,modal=document.createElement('div');modal.className='modal-backdrop';modal.innerHTML=`<div class="modal"><div class="modal-head"><h2>Conversation settings</h2><button class="close">×</button></div><div class="security-row"><span class="security-symbol">⊘</span><div><strong>${blocked?'Unblock':'Block'} conversation</strong><small>${blocked?'Resume messages':'Stop messages and calls'}</small></div><button class="text-btn" id="blockChat">${blocked?'Unblock':'Block'}</button></div></div>`;document.body.appendChild(modal);modal.querySelector('.close').onclick=()=>modal.remove();modal.querySelector('#blockChat').onclick=async()=>{try{await RoomBridgeAPI.blockConversation(c.id,!blocked);c.blocked_at=blocked?null:new Date().toISOString();modal.remove();renderMessages(c.id)}catch(error){showToast(error.message)}}}
async function createGroupConversation(){const name=prompt('Conversation name');if(!name?.trim())return;try{const result=await RoomBridgeAPI.createConversation({kind:'group',title:name.trim(),memberIds:[]});state.conversations=[];renderMessages(result.id)}catch(error){showToast(error.message)}}

async function renderHousehold(){
  try{
    const households=(await RoomBridgeAPI.households()).households;
    if(!households.length){app.innerHTML=appShell('household','<main class="dashboard"><div class="empty"><h2>Plan a household together</h2><p>Create a private planning space, then invite people you trust.</p><button class="btn btn-primary" id="createHousehold">Create household</button></div></main>');bindMainNav();document.querySelector('#createHousehold').onclick=createHousehold;return}
    const detail=await RoomBridgeAPI.household(households[0].id),h=detail.household,members=detail.members;
    state.household=detail;
    app.innerHTML=appShell('household',`<main class="dashboard household-page"><section class="household-hero"><div><span class="eyebrow">Prospective household</span><h1>${escapeHtml(h.name)}</h1><p>${members.length} member${members.length===1?'':'s'} planning a home together</p></div><button class="btn btn-primary" id="inviteMember">+ Invite member</button></section><section class="household-section"><div class="section-head"><h2>Household members</h2><span>Private planning space</span></div><div class="member-grid">${members.map(m=>`<div class="member-plan"><div class="person-avatar">${escapeHtml(m.name).slice(0,2).toUpperCase()}</div><strong>${escapeHtml(m.name)}</strong><small>${escapeHtml(m.role)}</small>${m.role!=='owner'?`<button data-remove-member="${m.user_id}">Remove</button>`:''}</div>`).join('')}</div></section><section class="household-section"><div class="section-head"><h2>Shared shortlist</h2><span>${detail.shortlist.length} properties</span></div>${detail.shortlist.length?detail.shortlist.map(x=>`<div class="tool-card"><strong>${escapeHtml(x.title)}</strong><span>$${Number(x.rent).toLocaleString()} · ${escapeHtml(x.city)} · vote: ${escapeHtml(x.vote||'—')}</span></div>`).join(''):'<div class="empty">No properties have been shortlisted yet.</div>'}</section></main>`);
    bindMainNav();document.querySelector('#inviteMember').onclick=inviteToHousehold;document.querySelectorAll('[data-remove-member]').forEach(b=>b.onclick=async()=>{try{await RoomBridgeAPI.removeHouseholdMember(h.id,b.dataset.removeMember);renderHousehold()}catch(error){showToast(error.message)}});
  }catch(error){showToast(error.message)}
}
function shortlistCard(l,h,members){const votes=h.votes[l.id]||{},yes=Object.values(votes).filter(x=>x==='yes').length;return `<article class="shortlist-card"><div class="shortlist-art">${roomIllustration(l,true)}</div><div><span class="tag">${l.category}</span><h3>${l.title}</h3><p>$${l.rent}/mo · ${l.area} · ${l.beds} bedroom</p><strong>${yes} yes vote${yes===1?'':'s'}</strong><div class="vote-members"><span>Your vote: ${votes.me||'—'}</span>${members.map(m=>`<span title="${m.name}">${m.initials}: ${votes[m.id]||'—'}</span>`).join('')}</div><div class="vote-actions"><button data-vote="${l.id}-me" data-choice="yes">Like</button><button data-vote="${l.id}-me" data-choice="maybe">Maybe</button><button data-vote="${l.id}-me" data-choice="no">Pass</button></div></div></article>`}
async function createHousehold(){const name=prompt('Household name');if(!name?.trim())return;try{await RoomBridgeAPI.createHousehold({name:name.trim()});renderHousehold()}catch(error){showToast(error.message)}}
async function inviteToHousehold(){const userId=prompt('Enter the member user ID');if(!userId?.trim())return;try{await RoomBridgeAPI.addHouseholdMember(state.household.household.id,userId.trim());renderHousehold()}catch(error){showToast(error.message)}}

async function openLeaseWorkflow(listingId){
  const l=state.listings.find(x=>String(x.id)===String(listingId));if(!l||l.owner_id!==state.user.id)return showToast('Only the listing owner can manage its lease handoff');
  try{const workflows=(await RoomBridgeAPI.leaseWorkflows()).workflows,existing=workflows.find(x=>x.listing_id===listingId),data=existing||{transfer_type:'Lease assignment',replacement_date:'',fee:0,landlord_status:'not_contacted',steps:{}},modal=document.createElement('div');modal.className='modal-backdrop listing-backdrop';modal.innerHTML=`<div class="modal lease-modal"><div class="modal-head"><h2>${escapeHtml(l.title)} lease handoff</h2><button class="close">×</button></div><div class="lease-summary"><label>Transfer type<select id="leaseType">${['Sublease','Lease assignment','Roommate replacement'].map(x=>`<option ${x===data.transfer_type?'selected':''}>${x}</option>`).join('')}</select></label><label>Replacement date<input id="replacementDate" type="date" value="${data.replacement_date||''}"></label><label>Transfer fees ($)<input id="transferFee" type="number" min="0" value="${Number(data.fee||0)}"></label><label>Landlord status<select id="approval">${['not_contacted','awaiting_response','reviewing','approved','changes_requested'].map(x=>`<option ${x===data.landlord_status?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select></label></div><div class="lease-steps">${[['details','Transfer details'],['candidate','Incoming tenant application'],['documents','Secure lease documents'],['landlord','Landlord approval'],['signing','Sign assignment and hand over keys']].map(([k,v])=>`<label><input type="checkbox" data-lease-step="${k}" ${data.steps?.[k]?'checked':''}><span><strong>${v}</strong></span></label>`).join('')}</div><button class="btn btn-primary btn-wide" id="saveLease">Save lease workflow</button></div>`;document.body.appendChild(modal);modal.querySelector('.close').onclick=()=>modal.remove();modal.querySelector('#saveLease').onclick=async()=>{const payload={listingId,transferType:modal.querySelector('#leaseType').value,replacementDate:modal.querySelector('#replacementDate').value,fee:Number(modal.querySelector('#transferFee').value),landlordStatus:modal.querySelector('#approval').value,steps:{}};modal.querySelectorAll('[data-lease-step]').forEach(x=>payload.steps[x.dataset.leaseStep]=x.checked);try{existing?await RoomBridgeAPI.updateLeaseWorkflow(existing.id,payload):await RoomBridgeAPI.createLeaseWorkflow(payload);modal.remove();showToast('Lease handoff saved')}catch(error){showToast(error.message)}}}catch(error){showToast(error.message)}
}

function normalizeMatch(p,index){
  const lifestyle=typeof p.lifestyle==='string'?JSON.parse(p.lifestyle||'{}'):(p.lifestyle||{}),languages=typeof p.languages==='string'?JSON.parse(p.languages||'[]'):(p.languages||[]);
  const breakdown=(p.explanation||[]).map(x=>({...x,label:x.name}));
  return {...p,id:p.user_id,name:p.name||'RoomBridge member',initials:(p.name||'RB').split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase(),age:'',country:p.country||'Private',city:p.city||'Location private',budget:Number(p.budget||0),move:p.move_date||'Flexible',room:p.room_type||'Flexible',need:p.scenario||'Looking for compatible housing',diet:p.diet||'No preference',languages,cleanliness:lifestyle.cleanliness||'Flexible',schedule:lifestyle.schedule||'Flexible',social:lifestyle.social||'Balanced',guests:lifestyle.guests||'Occasionally',smoking:lifestyle.smoking||'No',pets:lifestyle.pets||'No pets',gender:lifestyle.gender||'No preference',color:["#ffd9b8","#cce6ff","#e2d5ff","#cdebd4"][index%4],reasons:breakdown.filter(x=>x.matched).slice(0,3).map(x=>x.name)||['compatible preferences'],breakdown,score:Number(p.score||0),excluded:!!p.excluded};
}

function renderDashboard() {
  if(state.discovery==="housing") return renderListings();
  const first=(state.user.name||"there").split(" ")[0];
  const scored=state.matches,excluded=scored.filter(p=>p.excluded).length;
  const filtered=scored.filter(p=>!p.excluded).sort((a,b)=>b.score-a.score).filter(p=> state.filter==="All matches" || (state.filter==="Under budget"&&p.budget<=Number(state.user.budget||1300)) || (state.filter==="Private room"&&p.room==="Private room") || (state.filter==="Saved"&&state.saved.includes(p.id)));
  const groups=buildGroups(scored);
  app.innerHTML=`<div class="shell"><header class="topbar">${brand()}${mainNav('roommates')}<button class="avatar avatar-button" id="securityCenter" aria-label="Account and security">${(state.user.name||'RB').split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</button></header>
    <main class="dashboard"><section class="welcome"><div><h1>Good to see you, ${escapeHtml(first)}.</h1><p>Recommendations adapt as you tell us what works.</p></div><div class="view-toggle"><button class="${state.matchView==='people'?'active':''}" data-view="people">People</button><button class="${state.matchView==='groups'?'active':''}" data-view="groups">Groups of 3+</button></div></section>
    ${state.matchView==='people'?`<div class="filters filter-bar">${["All matches","Under budget","Private room","Saved"].map(f=>`<button class="filter ${state.filter===f?'active':''}" data-filter="${f}">${f}</button>`).join('')}<span class="deal-note">${excluded?`✓ ${excluded} conflict${excluded>1?'s':''} filtered by your deal-breakers`:"✓ Deal-breakers applied"}</span></div>`:''}
    <div class="content-grid"><section><div class="section-head"><h2>${state.matchView==='groups'?'Compatible roommate groups':'Your best matches'} <span style="color:var(--green)">✦</span></h2><span>${state.matchView==='groups'?groups.length+' groups':filtered.length+' people'}</span></div><div class="cards ${state.matchView==='groups'?'group-cards':''}">${state.matchView==='groups'?(groups.length?groups.map(groupCard).join(''):'<div class="empty">Complete your compatibility profile to build groups.</div>'):(filtered.length?filtered.map(profileCard).join(''):'<div class="empty">No matches in this view yet. Try another filter.</div>')}</div></section>
    <aside class="sidebar"><div class="side-card"><h3>Trust & verification</h3><div class="verification-list"><span><b class="verified">✓</b> Email verified</span><span><b class="${state.user.phoneVerified?'verified':'pending'}">${state.user.phoneVerified?'✓':'!'}</b> Phone ${state.user.phoneVerified?'verified':'not verified'}</span><span><b class="${state.user.institutionVerified?'verified':'pending'}">${state.user.institutionVerified?'✓':'!'}</b> School or employer ${state.user.institutionVerified?'verified':'optional'}</span></div><button class="btn btn-secondary btn-wide" id="manageSecurity">Manage verification</button></div>
    <div class="side-card"><h3>Stay safe on RoomBridge</h3><div class="safe-list"><div class="safe-item"><span class="safe-icon">✓</span><span>Meet by video before committing.</span></div><div class="safe-item"><span class="safe-icon">$</span><span>Never send money before viewing a home.</span></div><div class="safe-item"><span class="safe-icon">⌂</span><span>Confirm the lease and landlord.</span></div></div></div></aside></div></main></div>`;
  document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()});
  document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{state.matchView=b.dataset.view;render()});
  document.querySelectorAll("[data-save]").forEach(b=>b.onclick=()=>toggleSave(b.dataset.save));
  document.querySelectorAll("[data-connect]").forEach(b=>b.onclick=()=>openConnect(b.dataset.connect));
  document.querySelectorAll("[data-explain]").forEach(b=>b.onclick=()=>openExplanation(b.dataset.explain));
  document.querySelectorAll("[data-feedback]").forEach(b=>b.onclick=()=>setFeedback(b.dataset.id,b.dataset.feedback));
  document.querySelectorAll("[data-report-user]").forEach(b=>b.onclick=()=>openReportCenter("user",b.dataset.reportUser));
  document.querySelectorAll("[data-group]").forEach(b=>b.onclick=()=>showToast("Group introduction request sent!"));
  document.querySelector("#editProfile")?.addEventListener("click",()=>{state.step=1;state.screen="onboard";render()});
  bindMainNav();
  document.querySelector("#manageSecurity").onclick=openSecurityCenter;
}

function profileCard(p) {
  return `<article class="profile-card"><div class="card-top"><div class="person-avatar" style="background:${p.color}">${escapeHtml(p.initials)}</div><div class="person"><h3>${escapeHtml(p.name)}</h3><p>✓ Community verified · ${escapeHtml(p.country)}</p><p>${icon('pin')} ${escapeHtml(p.city)}</p></div><button class="match" data-explain="${escapeHtml(p.id)}" aria-label="Explain ${p.score}% match">${p.score}%</button></div><div class="card-body"><div class="need">${escapeHtml(p.need)}</div><div class="meta"><div>Monthly budget<strong>$${p.budget.toLocaleString()}</strong></div><div>Move-in<strong>${escapeHtml(p.move)}</strong></div><div>Room type<strong>${escapeHtml(p.room)}</strong></div><div>Lifestyle<strong>${escapeHtml(p.schedule)}</strong></div></div><div class="tags">${[p.diet,p.cleanliness,p.guests+' guests',...p.languages.slice(0,1)].map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join('')}</div><button class="why" data-explain="${escapeHtml(p.id)}">✦ Why you match: ${p.reasons.map(escapeHtml).join(" · ")} →</button><div class="feedback-row"><span>Improve recommendations</span><button class="${state.feedback[p.id]==='more'?'selected':''}" data-feedback="more" data-id="${escapeHtml(p.id)}">More like this</button><button class="${state.feedback[p.id]==='less'?'selected':''}" data-feedback="less" data-id="${escapeHtml(p.id)}">Less like this</button><button data-report-user="${escapeHtml(p.id)}">Report</button></div><div class="card-actions"><button class="btn ${state.saved.includes(p.id)?'btn-secondary':'btn-ghost'}" data-save="${escapeHtml(p.id)}">${state.saved.includes(p.id)?'♥ Saved':'♡ Save'}</button><button class="btn btn-primary" data-connect="${escapeHtml(p.id)}">Connect</button></div></div></article>`;
}

function groupCard(g) { return `<article class="profile-card group-card"><div class="group-head"><div class="avatar-stack">${g.members.map(m=>`<span style="background:${m.color}">${escapeHtml(m.initials)}</span>`).join('')}</div><div class="match">${g.score}%</div></div><div class="card-body"><h3>${g.members.map(m=>escapeHtml(m.name.split(' ')[0])).join(', ')}</h3><p class="subtext">Potential household · Combined budget $${g.budget.toLocaleString()}</p><div class="group-members">${g.members.map(m=>`<div><span>${escapeHtml(m.initials)}</span><p><strong>${escapeHtml(m.name)}</strong><small>${escapeHtml(m.city)} · $${m.budget}</small></p></div>`).join('')}</div><p class="why">✦ Group strengths: ${g.reasons.map(escapeHtml).join(' · ')}</p><button class="btn btn-primary btn-wide" data-group="${escapeHtml(g.id)}">Start a group conversation</button></div></article>`; }

async function setFeedback(id,value){try{await RoomBridgeAPI.matchFeedback(id,value);state.feedback[id]=value;const result=await RoomBridgeAPI.matches();state.matches=result.matches.map(normalizeMatch);render();showToast("Thanks — your recommendations were updated")}catch(error){showToast(error.message)}}
function openExplanation(id){const p=state.matches.find(x=>String(x.id)===String(id));if(!p)return;const modal=document.createElement("div");modal.className="modal-backdrop";modal.innerHTML=`<div class="modal"><div class="modal-head"><div><span class="eyebrow" style="color:var(--green)">Transparent matching</span><h2>${p.score}% match with ${escapeHtml(p.name.split(' ')[0])}</h2></div><button class="close">×</button></div><p class="subtext">Scores use only the preferences you provided. Required choices filter conflicts before scoring.</p><div class="score-breakdown">${(p.breakdown||[]).map(x=>`<div><span>${x.matched?'✓':'–'} ${escapeHtml(x.label)}<small>${escapeHtml(x.detail)}</small></span><strong>${x.points}/${x.max}</strong></div>`).join('')}</div></div>`;document.body.appendChild(modal);modal.querySelector('.close').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};}

async function toggleSave(id) { const saving=!state.saved.includes(id);try{await RoomBridgeAPI.saveProfileCard(id,saving);state.saved=saving?[...state.saved,id]:state.saved.filter(x=>x!==id);render();showToast(saving?"Profile saved":"Removed from saved")}catch(error){showToast(error.message)} }
function openConnect(id) {
  const p=state.matches.find(x=>String(x.id)===String(id));if(!p)return;
  const modal=document.createElement("div"); modal.className="modal-backdrop";
  modal.innerHTML=`<div class="modal"><div class="modal-head"><div><span class="eyebrow" style="color:var(--green)">Start a conversation</span><h2>Connect with ${escapeHtml(p.name.split(' ')[0])}</h2></div><button class="close">×</button></div><p class="subtext">A thoughtful introduction gets better replies.</p><div class="message-box">Hi ${escapeHtml(p.name.split(' ')[0])}! I saw that we're both looking around ${escapeHtml(p.city.split(',')[0])} and our housing preferences seem compatible. Would you be open to chatting about your plans?</div><label>Add a personal note<textarea id="note" placeholder="Mention your move date, schedule, or what matters to you..."></textarea></label><button class="btn btn-primary btn-wide" id="send">Send connection request →</button></div>`;
  document.body.appendChild(modal); modal.querySelector(".close").onclick=()=>modal.remove(); modal.onclick=e=>{if(e.target===modal)modal.remove()}; modal.querySelector("#send").onclick=async()=>{try{const result=await RoomBridgeAPI.createConversation({kind:'private',title:`Chat with ${p.name}`,memberIds:[p.id]});const note=modal.querySelector('#note').value.trim();await RoomBridgeAPI.sendMessage(result.id,{body:note||`Hi ${p.name.split(' ')[0]}! Would you be open to chatting about your housing plans?`});state.conversations=[];modal.remove();showToast(`Connection request sent to ${p.name.split(' ')[0]}!`)}catch(error){showToast(error.message)}};
}
function openSecurityCenter() {
  const modal=document.createElement("div");modal.className="modal-backdrop";
  modal.innerHTML=`<div class="modal"><div class="modal-head"><div><span class="eyebrow" style="color:var(--green)">Account</span><h2>Security & verification</h2></div><button class="close">×</button></div><div class="account-email">Signed in as <strong>${escapeHtml(state.user.email)}</strong></div><div class="security-options"><div class="security-row"><span class="security-symbol">✉</span><div><strong>Email address</strong><small>${escapeHtml(state.user.email)} · Verified</small></div><b class="status-pill verified-pill">Verified</b></div><div class="security-row"><span class="security-symbol">◫</span><div><strong>Phone number</strong><small>${escapeHtml(state.user.phoneVerified?(state.user.phone||'Verified'):'Protect your account and build trust')}</small></div><button class="text-btn" id="verifyPhone">${state.user.phoneVerified?'Update':'Verify'}</button></div><div class="security-row"><span class="security-symbol">⌂</span><div><strong>School or employer</strong><small>${state.user.institutionVerified?'Institutional email verified':'Optional community verification'}</small></div><button class="text-btn" id="verifyInstitution">${state.user.institutionVerified?'Update':'Verify'}</button></div></div><button class="btn btn-ghost btn-wide" id="signOut">Sign out</button></div>`;
  document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector(".close").onclick=close;modal.onclick=e=>{if(e.target===modal)close()};
  modal.querySelector("#signOut").onclick=async()=>{try{await RoomBridgeAPI.logout()}catch{}sessionStorage.removeItem("rbSession");state.user=null;state.screen="auth";state.authMode="signin";close();render();showToast("You have been signed out")};
  modal.querySelector("#verifyPhone").onclick=()=>openVerificationInput("phone",modal);
  modal.querySelector("#verifyInstitution").onclick=()=>openVerificationInput("institution",modal);
}
function openVerificationInput(type, previousModal) {
  previousModal.remove();const isPhone=type==="phone";const modal=document.createElement("div");modal.className="modal-backdrop";
  modal.innerHTML=`<form class="modal" id="extraVerify"><div class="modal-head"><div><span class="eyebrow" style="color:var(--green)">Optional verification</span><h2>${isPhone?'Verify your phone':'Verify school or employer'}</h2></div><button type="button" class="close">×</button></div><p class="subtext">${isPhone?'We’ll use this for account security and never show it publicly.':'Use an official .edu or work email. Your address stays private.'}</p><label>${isPhone?'Phone number':'Institutional email'}<input name="destination" required ${isPhone?'type="tel" placeholder="+1 201 555 0123"':'type="email" placeholder="you@university.edu"'}></label><p class="auth-error" id="authError"></p><button class="btn btn-primary btn-wide">Send verification code</button></form>`;document.body.appendChild(modal);modal.querySelector(".close").onclick=()=>modal.remove();
  modal.querySelector("#extraVerify").onsubmit=async e=>{e.preventDefault();const destination=new FormData(e.target).get("destination").trim(),error=modal.querySelector("#authError");if(!isPhone&&!/(\.edu$|\.(ac|edu)\.[a-z]{2}$|@[a-z0-9.-]+\.[a-z]{2,}$)/i.test(destination)){error.textContent="Enter a valid university or employer email.";return}try{const request=await RoomBridgeAPI.requestContactVerification({destination,purpose:type});modal.innerHTML=`<form class="modal-inner" id="codeForm"><div class="modal-head"><h2>Enter verification code</h2><button type="button" class="close">×</button></div><p class="subtext">Code sent to <strong>${escapeHtml(destination)}</strong>.</p>${request.demoCode?`<div class="demo-code"><span>Demo verification code</span><strong>${escapeHtml(request.demoCode)}</strong></div>`:""}<label>6-digit code<input name="code" required maxlength="6" inputmode="numeric" placeholder="000000"></label><p class="auth-error" id="authError"></p><button class="btn btn-primary btn-wide">Complete verification</button></form>`;modal.querySelector(".close").onclick=()=>modal.remove();modal.querySelector("#codeForm").onsubmit=async ev=>{ev.preventDefault();try{const result=await RoomBridgeAPI.verify({verificationId:request.verificationId,code:new FormData(ev.target).get("code")});state.user={...state.user,...result.user};sessionStorage.setItem("rbSession",JSON.stringify(state.user));modal.remove();render();showToast(`${isPhone?'Phone':'Institution'} verified successfully`)}catch(apiError){modal.querySelector("#authError").textContent=apiError.message}}}catch(apiError){error.textContent=apiError.message}};
}
function showToast(msg){const t=document.querySelector("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2800)}
async function bootstrap(){
  try{const result=await RoomBridgeAPI.me(),[profileResult,searchResult,listingResult,savedResult]=await Promise.all([RoomBridgeAPI.profile(),RoomBridgeAPI.savedSearches(),RoomBridgeAPI.listings(),RoomBridgeAPI.savedProfiles()]),profile=profileResult.profile,searches=searchResult.searches;state.user={...result.user,...(profile||{})};state.savedSearches=searches;state.saved=savedResult.ids;state.alertsEnabled=searches.some(x=>!!x.alerts_enabled);state.listings=(listingResult.listings||[]).map((l,i)=>({...l,area:l.neighborhood||"Area shared after connecting",available:l.available_date||"",lease:l.lease_duration||"Flexible",deposit:Number(l.deposit||0),rent:Number(l.rent),furnished:l.furnished||"Not specified",utilities:l.utilities||"Ask host",parking:l.parking||"Ask host",laundry:l.laundry||"Ask host",accessibility:l.accessibility||"Ask host",amenities:l.amenities||[],beds:1,baths:1,host:"Host",commutes:{NYU:0,"Columbia University":0,"Google NYC":0,"Newark Penn":0},lat:20+(i*17)%65,lng:20+(i*23)%65,color:["#d9e8da","#dce7f5","#f0dfd4"][i%3],accent:["#205c45","#315f8b","#945c3d"][i%3],video:false}));if(profile){const matches=await RoomBridgeAPI.matches();state.matches=matches.matches.map(normalizeMatch)}sessionStorage.setItem("rbSession",JSON.stringify(result.user));state.screen=profile?"dashboard":"onboard"}catch{sessionStorage.removeItem("rbSession");state.user=null;state.screen="auth"}render()
}
bootstrap();
